apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: secret-manager-trust-bundle
spec:
  sources:
  # This only works because `app.trust.namespace=secret-manager-system`, see https://cert-manager.io/docs/trust/trust-manager/installation/#trust-namespace
  - secret:
      name: secret-manager-cert 
      key: ca.crt
  target:
    configMap:
      key: trust-bundle.pem
    namespaceSelector:
      matchLabels:
        cp.ei.telekom.de/secret-manager: enabled