with-expecter: True
mockname: "Mock{{.InterfaceName}}"
dir: "../test/mocks"
outpkg: "mocks"
filename: "mock_{{.InterfaceName}}.go"
packages:
  cp.ei.telekom.de/common-server/pkg/store:
    # place your package-specific config here
    config:
    interfaces:
      # select the interfaces you want mocked
      ObjectStore:
        # Modify package-level config for this specific interface (if applicable)
        config: