version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: "gomod"
    schedule:
      interval: "daily"
    directories:
      - common
      - common-server
      - identity
      - gateway
      - secret-manager
    groups:
      default: 
        update-types:
          - patch
          - minor