# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...

builds:
  - id: gateway
    dir: gateway
    main: cmd/main.go
    binary: gateway-manager
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  header: >-
    # 🚀 Release {{ .Version }}
  footer: >-

    ---

    # Docker Images

    - `docker pull ghcr.io/telekom/controlplane-mono/gateway:{{ .Tag }}`

sboms:
  - artifacts: archive

kos:
  - id: gateway
    build: gateway
    main: .
    working_dir: gateway/cmd
    base_image: gcr.io/distroless/static:nonroot
    user: 65532:65532
    repositories:
      - ghcr.io/telekom/controlplane-mono/gateway
    labels:
      org.opencontainers.image.source: https://github.com/telekom/controlplane-mono/gateway
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.description: |
        This is a test description
    tags:
      - latest
      - "{{.Tag}}"
      - "{{if not .Prerelease}}stable{{end}}"
    bare: true
    platforms:
      - linux/amd64
      - linux/arm64
