excludes:
  paths:
  - pattern: "test-data/**"
    reason: "TEST_OF"
    comment: "This directory contains test data which are not distributed."
  - pattern: "CONTRIBUTING.md"
    reason: DOCUMENTATION_OF
    comment: "This file contains contribution guidelines which are not distributed."
  - pattern: "README.md"
    reason: DOCUMENTATION_OF
    comment: "This file contains project description which is not distributed."
  - pattern: ".github/**"
    reason: "BUILD_TOOL_OF"
    comment: "This directory contains GitHub Actions workflows which are not distributed."
  - pattern: "*_test.go"
    reason: "TEST_OF"
    comment: "This file contains test code which is not distributed."
  - pattern: "test_*.go"
    reason: "TEST_OF"
    comment: "This file contains test code which is not distributed."

curations:
  packages:
    - id: "Go::golang.org/x/tools"
      curations: 
        concluded_license: BSD-3-Clause
    - id: "Go::golang.org/x/net"
      curations: 
        concluded_license: BSD-3-Clause
    - id: "Go::golang.org/x/text"
      curations: 
        concluded_license: BSD-3-Clause
    - id: "Go::golang.org/x/sys"
      curations: 
        concluded_license: BSD-3-Clause
    - id: "Go::golang.org/x/mod"
      curations: 
        concluded_license: BSD-3-Clause
    - id: "Go::golang.org/x/time"
      curations: 
        concluded_license: BSD-3-Clause
    - id: "Go::golang.org/x/exp"
      curations: 
        concluded_license: BSD-3-Clause
    - id: "Go::golang.org/x/sync"
      curations: 
        concluded_license: BSD-3-Clause
    - id: "Go::golang.org/x/term"
      curations: 
        concluded_license: BSD-3-Clause