# Patch for Prometheus ServiceMonitor to enable secure TLS configuration
# using certificates managed by cert-manager
- op: add
  path: /spec/endpoints/0/tlsConfig
  value:
    insecureSkipVerify: false
    ca:
      secret:
        name: secret-manager-cert
        key: ca.crt