# permissions for end users to view routes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/managed-by: kustomize
  name: route-viewer-role
rules:
- apiGroups:
  - gateway.cp.ei.telekom.de
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.cp.ei.telekom.de
  resources:
  - routes/status
  verbs:
  - get
