# random comment
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  config.yaml: |- 
  {{ .Values.config | toYaml | nindent 4 }}