- id: "Go::github.com/emicklei/go-restful/v3"
  curations:
    concluded_license: MIT
    comment: |
      This project is licensed under the MIT License. See the LICENSE file for more details.
      The copyright garbage found by ORT is just a link to the license file.
      TODO: this could potentially be added to the copyright-garbage file.