// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

const (
	Access_tokenScopes = "access_token.Scopes"
)

// Defines values for AccessTokenCategory.
const (
	ACCESS   AccessTokenCategory = "ACCESS"
	ADMIN    AccessTokenCategory = "ADMIN"
	ID       AccessTokenCategory = "ID"
	INTERNAL AccessTokenCategory = "INTERNAL"
	USERINFO AccessTokenCategory = "USERINFO"
)

// Defines values for PartialImportRepresentationPolicy.
const (
	FAIL      PartialImportRepresentationPolicy = "FAIL"
	OVERWRITE PartialImportRepresentationPolicy = "OVERWRITE"
	SKIP      PartialImportRepresentationPolicy = "SKIP"
)

// Defines values for PolicyRepresentationDecisionStrategy.
const (
	PolicyRepresentationDecisionStrategyAFFIRMATIVE PolicyRepresentationDecisionStrategy = "AFFIRMATIVE"
	PolicyRepresentationDecisionStrategyCONSENSUS   PolicyRepresentationDecisionStrategy = "CONSENSUS"
	PolicyRepresentationDecisionStrategyUNANIMOUS   PolicyRepresentationDecisionStrategy = "UNANIMOUS"
)

// Defines values for PolicyRepresentationLogic.
const (
	NEGATIVE PolicyRepresentationLogic = "NEGATIVE"
	POSITIVE PolicyRepresentationLogic = "POSITIVE"
)

// Defines values for ResourceServerRepresentationDecisionStrategy.
const (
	ResourceServerRepresentationDecisionStrategyAFFIRMATIVE ResourceServerRepresentationDecisionStrategy = "AFFIRMATIVE"
	ResourceServerRepresentationDecisionStrategyCONSENSUS   ResourceServerRepresentationDecisionStrategy = "CONSENSUS"
	ResourceServerRepresentationDecisionStrategyUNANIMOUS   ResourceServerRepresentationDecisionStrategy = "UNANIMOUS"
)

// Defines values for ResourceServerRepresentationPolicyEnforcementMode.
const (
	DISABLED   ResourceServerRepresentationPolicyEnforcementMode = "DISABLED"
	ENFORCING  ResourceServerRepresentationPolicyEnforcementMode = "ENFORCING"
	PERMISSIVE ResourceServerRepresentationPolicyEnforcementMode = "PERMISSIVE"
)

// AccessToken defines model for AccessToken.
type AccessToken struct {
	Acr                 *string                   `json:"acr,omitempty"`
	Address             *AddressClaimSet          `json:"address,omitempty"`
	AllowedOrigins      *[]string                 `json:"allowed-origins,omitempty"`
	AtHash              *string                   `json:"at_hash,omitempty"`
	AuthTime            *int64                    `json:"auth_time,omitempty"`
	Authorization       *AccessTokenAuthorization `json:"authorization,omitempty"`
	Azp                 *string                   `json:"azp,omitempty"`
	Birthdate           *string                   `json:"birthdate,omitempty"`
	CHash               *string                   `json:"c_hash,omitempty"`
	Category            *AccessTokenCategory      `json:"category,omitempty"`
	ClaimsLocales       *string                   `json:"claims_locales,omitempty"`
	Cnf                 *AccessTokenCertConf      `json:"cnf,omitempty"`
	Email               *string                   `json:"email,omitempty"`
	EmailVerified       *bool                     `json:"email_verified,omitempty"`
	Exp                 *int64                    `json:"exp,omitempty"`
	FamilyName          *string                   `json:"family_name,omitempty"`
	Gender              *string                   `json:"gender,omitempty"`
	GivenName           *string                   `json:"given_name,omitempty"`
	Iat                 *int64                    `json:"iat,omitempty"`
	Iss                 *string                   `json:"iss,omitempty"`
	Jti                 *string                   `json:"jti,omitempty"`
	Locale              *string                   `json:"locale,omitempty"`
	MiddleName          *string                   `json:"middle_name,omitempty"`
	Name                *string                   `json:"name,omitempty"`
	Nbf                 *int64                    `json:"nbf,omitempty"`
	Nickname            *string                   `json:"nickname,omitempty"`
	Nonce               *string                   `json:"nonce,omitempty"`
	OtherClaims         *map[string]interface{}   `json:"otherClaims,omitempty"`
	PhoneNumber         *string                   `json:"phone_number,omitempty"`
	PhoneNumberVerified *bool                     `json:"phone_number_verified,omitempty"`
	Picture             *string                   `json:"picture,omitempty"`
	PreferredUsername   *string                   `json:"preferred_username,omitempty"`
	Profile             *string                   `json:"profile,omitempty"`
	RealmAccess         *AccessTokenAccess        `json:"realm_access,omitempty"`
	SHash               *string                   `json:"s_hash,omitempty"`
	Scope               *string                   `json:"scope,omitempty"`
	SessionState        *string                   `json:"session_state,omitempty"`
	Sub                 *string                   `json:"sub,omitempty"`
	TrustedCerts        *[]string                 `json:"trusted-certs,omitempty"`
	Typ                 *string                   `json:"typ,omitempty"`
	UpdatedAt           *int64                    `json:"updated_at,omitempty"`
	Website             *string                   `json:"website,omitempty"`
	Zoneinfo            *string                   `json:"zoneinfo,omitempty"`
}

// AccessTokenCategory defines model for AccessToken.Category.
type AccessTokenCategory string

// AccessTokenAccess defines model for AccessToken-Access.
type AccessTokenAccess struct {
	Roles        *[]string `json:"roles,omitempty"`
	VerifyCaller *bool     `json:"verify_caller,omitempty"`
}

// AccessTokenAuthorization defines model for AccessToken-Authorization.
type AccessTokenAuthorization struct {
	Permissions *[]Permission `json:"permissions,omitempty"`
}

// AccessTokenCertConf defines model for AccessToken-CertConf.
type AccessTokenCertConf struct {
	X5tS256 *string `json:"x5t#S256,omitempty"`
}

// AddressClaimSet defines model for AddressClaimSet.
type AddressClaimSet struct {
	Country       *string `json:"country,omitempty"`
	Formatted     *string `json:"formatted,omitempty"`
	Locality      *string `json:"locality,omitempty"`
	PostalCode    *string `json:"postal_code,omitempty"`
	Region        *string `json:"region,omitempty"`
	StreetAddress *string `json:"street_address,omitempty"`
}

// AdminEventRepresentation defines model for AdminEventRepresentation.
type AdminEventRepresentation struct {
	AuthDetails    *AuthDetailsRepresentation `json:"authDetails,omitempty"`
	Error          *string                    `json:"error,omitempty"`
	OperationType  *string                    `json:"operationType,omitempty"`
	RealmId        *string                    `json:"realmId,omitempty"`
	Representation *string                    `json:"representation,omitempty"`
	ResourcePath   *string                    `json:"resourcePath,omitempty"`
	ResourceType   *string                    `json:"resourceType,omitempty"`
	Time           *int64                     `json:"time,omitempty"`
}

// AuthDetailsRepresentation defines model for AuthDetailsRepresentation.
type AuthDetailsRepresentation struct {
	ClientId  *string `json:"clientId,omitempty"`
	IpAddress *string `json:"ipAddress,omitempty"`
	RealmId   *string `json:"realmId,omitempty"`
	UserId    *string `json:"userId,omitempty"`
}

// AuthenticationExecutionExportRepresentation defines model for AuthenticationExecutionExportRepresentation.
type AuthenticationExecutionExportRepresentation struct {
	Authenticator       *string `json:"authenticator,omitempty"`
	AuthenticatorConfig *string `json:"authenticatorConfig,omitempty"`
	AuthenticatorFlow   *bool   `json:"authenticatorFlow,omitempty"`
	AutheticatorFlow    *bool   `json:"autheticatorFlow,omitempty"`
	FlowAlias           *string `json:"flowAlias,omitempty"`
	Priority            *int32  `json:"priority,omitempty"`
	Requirement         *string `json:"requirement,omitempty"`
	UserSetupAllowed    *bool   `json:"userSetupAllowed,omitempty"`
}

// AuthenticationExecutionInfoRepresentation defines model for AuthenticationExecutionInfoRepresentation.
type AuthenticationExecutionInfoRepresentation struct {
	Alias                *string   `json:"alias,omitempty"`
	AuthenticationConfig *string   `json:"authenticationConfig,omitempty"`
	AuthenticationFlow   *bool     `json:"authenticationFlow,omitempty"`
	Configurable         *bool     `json:"configurable,omitempty"`
	DisplayName          *string   `json:"displayName,omitempty"`
	FlowId               *string   `json:"flowId,omitempty"`
	Id                   *string   `json:"id,omitempty"`
	Index                *int32    `json:"index,omitempty"`
	Level                *int32    `json:"level,omitempty"`
	ProviderId           *string   `json:"providerId,omitempty"`
	Requirement          *string   `json:"requirement,omitempty"`
	RequirementChoices   *[]string `json:"requirementChoices,omitempty"`
}

// AuthenticationExecutionRepresentation defines model for AuthenticationExecutionRepresentation.
type AuthenticationExecutionRepresentation struct {
	Authenticator       *string `json:"authenticator,omitempty"`
	AuthenticatorConfig *string `json:"authenticatorConfig,omitempty"`
	AuthenticatorFlow   *bool   `json:"authenticatorFlow,omitempty"`
	AutheticatorFlow    *bool   `json:"autheticatorFlow,omitempty"`
	FlowId              *string `json:"flowId,omitempty"`
	Id                  *string `json:"id,omitempty"`
	ParentFlow          *string `json:"parentFlow,omitempty"`
	Priority            *int32  `json:"priority,omitempty"`
	Requirement         *string `json:"requirement,omitempty"`
}

// AuthenticationFlowRepresentation defines model for AuthenticationFlowRepresentation.
type AuthenticationFlowRepresentation struct {
	Alias                    *string                                        `json:"alias,omitempty"`
	AuthenticationExecutions *[]AuthenticationExecutionExportRepresentation `json:"authenticationExecutions,omitempty"`
	BuiltIn                  *bool                                          `json:"builtIn,omitempty"`
	Description              *string                                        `json:"description,omitempty"`
	Id                       *string                                        `json:"id,omitempty"`
	ProviderId               *string                                        `json:"providerId,omitempty"`
	TopLevel                 *bool                                          `json:"topLevel,omitempty"`
}

// AuthenticatorConfigInfoRepresentation defines model for AuthenticatorConfigInfoRepresentation.
type AuthenticatorConfigInfoRepresentation struct {
	HelpText   *string                         `json:"helpText,omitempty"`
	Name       *string                         `json:"name,omitempty"`
	Properties *[]ConfigPropertyRepresentation `json:"properties,omitempty"`
	ProviderId *string                         `json:"providerId,omitempty"`
}

// AuthenticatorConfigRepresentation defines model for AuthenticatorConfigRepresentation.
type AuthenticatorConfigRepresentation struct {
	Alias  *string                 `json:"alias,omitempty"`
	Config *map[string]interface{} `json:"config,omitempty"`
	Id     *string                 `json:"id,omitempty"`
}

// CertificateRepresentation defines model for CertificateRepresentation.
type CertificateRepresentation struct {
	Certificate *string `json:"certificate,omitempty"`
	Kid         *string `json:"kid,omitempty"`
	PrivateKey  *string `json:"privateKey,omitempty"`
	PublicKey   *string `json:"publicKey,omitempty"`
}

// ClientInitialAccessCreatePresentation defines model for ClientInitialAccessCreatePresentation.
type ClientInitialAccessCreatePresentation struct {
	Count      *int32 `json:"count,omitempty"`
	Expiration *int32 `json:"expiration,omitempty"`
}

// ClientInitialAccessPresentation defines model for ClientInitialAccessPresentation.
type ClientInitialAccessPresentation struct {
	Count          *int32  `json:"count,omitempty"`
	Expiration     *int32  `json:"expiration,omitempty"`
	Id             *string `json:"id,omitempty"`
	RemainingCount *int32  `json:"remainingCount,omitempty"`
	Timestamp      *int32  `json:"timestamp,omitempty"`
	Token          *string `json:"token,omitempty"`
}

// ClientRepresentation defines model for ClientRepresentation.
type ClientRepresentation struct {
	Access                             *map[string]interface{}         `json:"access,omitempty"`
	AdminUrl                           *string                         `json:"adminUrl,omitempty"`
	AlwaysDisplayInConsole             *bool                           `json:"alwaysDisplayInConsole,omitempty"`
	Attributes                         *map[string]interface{}         `json:"attributes,omitempty"`
	AuthenticationFlowBindingOverrides *map[string]interface{}         `json:"authenticationFlowBindingOverrides,omitempty"`
	AuthorizationServicesEnabled       *bool                           `json:"authorizationServicesEnabled,omitempty"`
	AuthorizationSettings              *ResourceServerRepresentation   `json:"authorizationSettings,omitempty"`
	BaseUrl                            *string                         `json:"baseUrl,omitempty"`
	BearerOnly                         *bool                           `json:"bearerOnly,omitempty"`
	ClientAuthenticatorType            *string                         `json:"clientAuthenticatorType,omitempty"`
	ClientId                           *string                         `json:"clientId,omitempty"`
	ConsentRequired                    *bool                           `json:"consentRequired,omitempty"`
	DefaultClientScopes                *[]string                       `json:"defaultClientScopes,omitempty"`
	DefaultRoles                       *[]string                       `json:"defaultRoles,omitempty"`
	Description                        *string                         `json:"description,omitempty"`
	DirectAccessGrantsEnabled          *bool                           `json:"directAccessGrantsEnabled,omitempty"`
	Enabled                            *bool                           `json:"enabled,omitempty"`
	FrontchannelLogout                 *bool                           `json:"frontchannelLogout,omitempty"`
	FullScopeAllowed                   *bool                           `json:"fullScopeAllowed,omitempty"`
	Id                                 *string                         `json:"id,omitempty"`
	ImplicitFlowEnabled                *bool                           `json:"implicitFlowEnabled,omitempty"`
	Name                               *string                         `json:"name,omitempty"`
	NodeReRegistrationTimeout          *int32                          `json:"nodeReRegistrationTimeout,omitempty"`
	NotBefore                          *int32                          `json:"notBefore,omitempty"`
	OptionalClientScopes               *[]string                       `json:"optionalClientScopes,omitempty"`
	Origin                             *string                         `json:"origin,omitempty"`
	Protocol                           *string                         `json:"protocol,omitempty"`
	ProtocolMappers                    *[]ProtocolMapperRepresentation `json:"protocolMappers,omitempty"`
	PublicClient                       *bool                           `json:"publicClient,omitempty"`
	RedirectUris                       *[]string                       `json:"redirectUris,omitempty"`
	RegisteredNodes                    *map[string]interface{}         `json:"registeredNodes,omitempty"`
	RegistrationAccessToken            *string                         `json:"registrationAccessToken,omitempty"`
	RootUrl                            *string                         `json:"rootUrl,omitempty"`
	Secret                             *string                         `json:"secret,omitempty"`
	ServiceAccountsEnabled             *bool                           `json:"serviceAccountsEnabled,omitempty"`
	StandardFlowEnabled                *bool                           `json:"standardFlowEnabled,omitempty"`
	SurrogateAuthRequired              *bool                           `json:"surrogateAuthRequired,omitempty"`
	WebOrigins                         *[]string                       `json:"webOrigins,omitempty"`
}

// ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentation defines model for ClientScopeEvaluateResource-ProtocolMapperEvaluationRepresentation.
type ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentation struct {
	ContainerId    *string `json:"containerId,omitempty"`
	ContainerName  *string `json:"containerName,omitempty"`
	ContainerType  *string `json:"containerType,omitempty"`
	MapperId       *string `json:"mapperId,omitempty"`
	MapperName     *string `json:"mapperName,omitempty"`
	ProtocolMapper *string `json:"protocolMapper,omitempty"`
}

// ClientScopeRepresentation defines model for ClientScopeRepresentation.
type ClientScopeRepresentation struct {
	Attributes      *map[string]interface{}         `json:"attributes,omitempty"`
	Description     *string                         `json:"description,omitempty"`
	Id              *string                         `json:"id,omitempty"`
	Name            *string                         `json:"name,omitempty"`
	Protocol        *string                         `json:"protocol,omitempty"`
	ProtocolMappers *[]ProtocolMapperRepresentation `json:"protocolMappers,omitempty"`
}

// ComponentRepresentation defines model for ComponentRepresentation.
type ComponentRepresentation struct {
	Config       *MultivaluedHashMap `json:"config,omitempty"`
	Id           *string             `json:"id,omitempty"`
	Name         *string             `json:"name,omitempty"`
	ParentId     *string             `json:"parentId,omitempty"`
	ProviderId   *string             `json:"providerId,omitempty"`
	ProviderType *string             `json:"providerType,omitempty"`
	SubType      *string             `json:"subType,omitempty"`
}

// ComponentTypeRepresentation defines model for ComponentTypeRepresentation.
type ComponentTypeRepresentation struct {
	HelpText   *string                         `json:"helpText,omitempty"`
	Id         *string                         `json:"id,omitempty"`
	Metadata   *map[string]interface{}         `json:"metadata,omitempty"`
	Properties *[]ConfigPropertyRepresentation `json:"properties,omitempty"`
}

// ConfigPropertyRepresentation defines model for ConfigPropertyRepresentation.
type ConfigPropertyRepresentation struct {
	DefaultValue *map[string]interface{} `json:"defaultValue,omitempty"`
	HelpText     *string                 `json:"helpText,omitempty"`
	Label        *string                 `json:"label,omitempty"`
	Name         *string                 `json:"name,omitempty"`
	Options      *[]string               `json:"options,omitempty"`
	Secret       *bool                   `json:"secret,omitempty"`
	Type         *string                 `json:"type,omitempty"`
}

// CredentialRepresentation defines model for CredentialRepresentation.
type CredentialRepresentation struct {
	CreatedDate    *int64  `json:"createdDate,omitempty"`
	CredentialData *string `json:"credentialData,omitempty"`
	Id             *string `json:"id,omitempty"`
	Priority       *int32  `json:"priority,omitempty"`
	SecretData     *string `json:"secretData,omitempty"`
	Temporary      *bool   `json:"temporary,omitempty"`
	Type           *string `json:"type,omitempty"`
	UserLabel      *string `json:"userLabel,omitempty"`
	Value          *string `json:"value,omitempty"`
}

// EventRepresentation defines model for EventRepresentation.
type EventRepresentation struct {
	ClientId  *string                 `json:"clientId,omitempty"`
	Details   *map[string]interface{} `json:"details,omitempty"`
	Error     *string                 `json:"error,omitempty"`
	IpAddress *string                 `json:"ipAddress,omitempty"`
	RealmId   *string                 `json:"realmId,omitempty"`
	SessionId *string                 `json:"sessionId,omitempty"`
	Time      *int64                  `json:"time,omitempty"`
	Type      *string                 `json:"type,omitempty"`
	UserId    *string                 `json:"userId,omitempty"`
}

// FederatedIdentityRepresentation defines model for FederatedIdentityRepresentation.
type FederatedIdentityRepresentation struct {
	IdentityProvider *string `json:"identityProvider,omitempty"`
	UserId           *string `json:"userId,omitempty"`
	UserName         *string `json:"userName,omitempty"`
}

// GlobalRequestResult defines model for GlobalRequestResult.
type GlobalRequestResult struct {
	FailedRequests  *[]string `json:"failedRequests,omitempty"`
	SuccessRequests *[]string `json:"successRequests,omitempty"`
}

// GroupRepresentation defines model for GroupRepresentation.
type GroupRepresentation struct {
	Access      *map[string]interface{} `json:"access,omitempty"`
	Attributes  *map[string]interface{} `json:"attributes,omitempty"`
	ClientRoles *map[string]interface{} `json:"clientRoles,omitempty"`
	Id          *string                 `json:"id,omitempty"`
	Name        *string                 `json:"name,omitempty"`
	Path        *string                 `json:"path,omitempty"`
	RealmRoles  *[]string               `json:"realmRoles,omitempty"`
	SubGroups   *[]GroupRepresentation  `json:"subGroups,omitempty"`
}

// IdentityProviderMapperRepresentation defines model for IdentityProviderMapperRepresentation.
type IdentityProviderMapperRepresentation struct {
	Config                 *map[string]interface{} `json:"config,omitempty"`
	Id                     *string                 `json:"id,omitempty"`
	IdentityProviderAlias  *string                 `json:"identityProviderAlias,omitempty"`
	IdentityProviderMapper *string                 `json:"identityProviderMapper,omitempty"`
	Name                   *string                 `json:"name,omitempty"`
}

// IdentityProviderRepresentation defines model for IdentityProviderRepresentation.
type IdentityProviderRepresentation struct {
	AddReadTokenRoleOnCreate  *bool                   `json:"addReadTokenRoleOnCreate,omitempty"`
	Alias                     *string                 `json:"alias,omitempty"`
	Config                    *map[string]interface{} `json:"config,omitempty"`
	DisplayName               *string                 `json:"displayName,omitempty"`
	Enabled                   *bool                   `json:"enabled,omitempty"`
	FirstBrokerLoginFlowAlias *string                 `json:"firstBrokerLoginFlowAlias,omitempty"`
	InternalId                *string                 `json:"internalId,omitempty"`
	LinkOnly                  *bool                   `json:"linkOnly,omitempty"`
	PostBrokerLoginFlowAlias  *string                 `json:"postBrokerLoginFlowAlias,omitempty"`
	ProviderId                *string                 `json:"providerId,omitempty"`
	StoreToken                *bool                   `json:"storeToken,omitempty"`
	TrustEmail                *bool                   `json:"trustEmail,omitempty"`
}

// KeyStoreConfig defines model for KeyStoreConfig.
type KeyStoreConfig struct {
	Format           *string `json:"format,omitempty"`
	KeyAlias         *string `json:"keyAlias,omitempty"`
	KeyPassword      *string `json:"keyPassword,omitempty"`
	RealmAlias       *string `json:"realmAlias,omitempty"`
	RealmCertificate *bool   `json:"realmCertificate,omitempty"`
	StorePassword    *string `json:"storePassword,omitempty"`
}

// KeysMetadataRepresentation defines model for KeysMetadataRepresentation.
type KeysMetadataRepresentation struct {
	Active *map[string]interface{}                                `json:"active,omitempty"`
	Keys   *[]KeysMetadataRepresentationKeyMetadataRepresentation `json:"keys,omitempty"`
}

// KeysMetadataRepresentationKeyMetadataRepresentation defines model for KeysMetadataRepresentation-KeyMetadataRepresentation.
type KeysMetadataRepresentationKeyMetadataRepresentation struct {
	Algorithm        *string `json:"algorithm,omitempty"`
	Certificate      *string `json:"certificate,omitempty"`
	Kid              *string `json:"kid,omitempty"`
	ProviderId       *string `json:"providerId,omitempty"`
	ProviderPriority *int64  `json:"providerPriority,omitempty"`
	PublicKey        *string `json:"publicKey,omitempty"`
	Status           *string `json:"status,omitempty"`
	Type             *string `json:"type,omitempty"`
}

// ManagementPermissionReference defines model for ManagementPermissionReference.
type ManagementPermissionReference struct {
	Enabled          *bool                   `json:"enabled,omitempty"`
	Resource         *string                 `json:"resource,omitempty"`
	ScopePermissions *map[string]interface{} `json:"scopePermissions,omitempty"`
}

// MappingsRepresentation defines model for MappingsRepresentation.
type MappingsRepresentation struct {
	ClientMappings *map[string]interface{} `json:"clientMappings,omitempty"`
	RealmMappings  *[]RoleRepresentation   `json:"realmMappings,omitempty"`
}

// MemoryInfoRepresentation defines model for MemoryInfoRepresentation.
type MemoryInfoRepresentation struct {
	Free           *int64  `json:"free,omitempty"`
	FreeFormated   *string `json:"freeFormated,omitempty"`
	FreePercentage *int64  `json:"freePercentage,omitempty"`
	Total          *int64  `json:"total,omitempty"`
	TotalFormated  *string `json:"totalFormated,omitempty"`
	Used           *int64  `json:"used,omitempty"`
	UsedFormated   *string `json:"usedFormated,omitempty"`
}

// MultivaluedHashMap defines model for MultivaluedHashMap.
type MultivaluedHashMap struct {
	Empty      *bool    `json:"empty,omitempty"`
	LoadFactor *float32 `json:"loadFactor,omitempty"`
	Threshold  *int32   `json:"threshold,omitempty"`
}

// PartialImportRepresentation defines model for PartialImportRepresentation.
type PartialImportRepresentation struct {
	Clients           *[]ClientRepresentation            `json:"clients,omitempty"`
	Groups            *[]GroupRepresentation             `json:"groups,omitempty"`
	IdentityProviders *[]IdentityProviderRepresentation  `json:"identityProviders,omitempty"`
	IfResourceExists  *string                            `json:"ifResourceExists,omitempty"`
	Policy            *PartialImportRepresentationPolicy `json:"policy,omitempty"`
	Roles             *RolesRepresentation               `json:"roles,omitempty"`
	Users             *[]UserRepresentation              `json:"users,omitempty"`
}

// PartialImportRepresentationPolicy defines model for PartialImportRepresentation.Policy.
type PartialImportRepresentationPolicy string

// PasswordPolicyTypeRepresentation defines model for PasswordPolicyTypeRepresentation.
type PasswordPolicyTypeRepresentation struct {
	ConfigType        *string `json:"configType,omitempty"`
	DefaultValue      *string `json:"defaultValue,omitempty"`
	DisplayName       *string `json:"displayName,omitempty"`
	Id                *string `json:"id,omitempty"`
	MultipleSupported *bool   `json:"multipleSupported,omitempty"`
}

// Permission defines model for Permission.
type Permission struct {
	Claims *map[string]interface{} `json:"claims,omitempty"`
	Rsid   *string                 `json:"rsid,omitempty"`
	Rsname *string                 `json:"rsname,omitempty"`
	Scopes *[]string               `json:"scopes,omitempty"`
}

// PolicyRepresentation defines model for PolicyRepresentation.
type PolicyRepresentation struct {
	Config           *map[string]interface{}               `json:"config,omitempty"`
	DecisionStrategy *PolicyRepresentationDecisionStrategy `json:"decisionStrategy,omitempty"`
	Description      *string                               `json:"description,omitempty"`
	Id               *string                               `json:"id,omitempty"`
	Logic            *PolicyRepresentationLogic            `json:"logic,omitempty"`
	Name             *string                               `json:"name,omitempty"`
	Owner            *string                               `json:"owner,omitempty"`
	Policies         *[]string                             `json:"policies,omitempty"`
	Resources        *[]string                             `json:"resources,omitempty"`
	ResourcesData    *[]ResourceRepresentation             `json:"resourcesData,omitempty"`
	Scopes           *[]string                             `json:"scopes,omitempty"`
	ScopesData       *[]ScopeRepresentation                `json:"scopesData,omitempty"`
	Type             *string                               `json:"type,omitempty"`
}

// PolicyRepresentationDecisionStrategy defines model for PolicyRepresentation.DecisionStrategy.
type PolicyRepresentationDecisionStrategy string

// PolicyRepresentationLogic defines model for PolicyRepresentation.Logic.
type PolicyRepresentationLogic string

// ProfileInfoRepresentation defines model for ProfileInfoRepresentation.
type ProfileInfoRepresentation struct {
	DisabledFeatures     *[]string `json:"disabledFeatures,omitempty"`
	ExperimentalFeatures *[]string `json:"experimentalFeatures,omitempty"`
	Name                 *string   `json:"name,omitempty"`
	PreviewFeatures      *[]string `json:"previewFeatures,omitempty"`
}

// ProtocolMapperRepresentation defines model for ProtocolMapperRepresentation.
type ProtocolMapperRepresentation struct {
	Config         *map[string]interface{} `json:"config,omitempty"`
	Id             *string                 `json:"id,omitempty"`
	Name           *string                 `json:"name,omitempty"`
	Protocol       *string                 `json:"protocol,omitempty"`
	ProtocolMapper *string                 `json:"protocolMapper,omitempty"`
}

// RealmEventsConfigRepresentation defines model for RealmEventsConfigRepresentation.
type RealmEventsConfigRepresentation struct {
	AdminEventsDetailsEnabled *bool     `json:"adminEventsDetailsEnabled,omitempty"`
	AdminEventsEnabled        *bool     `json:"adminEventsEnabled,omitempty"`
	EnabledEventTypes         *[]string `json:"enabledEventTypes,omitempty"`
	EventsEnabled             *bool     `json:"eventsEnabled,omitempty"`
	EventsExpiration          *int64    `json:"eventsExpiration,omitempty"`
	EventsListeners           *[]string `json:"eventsListeners,omitempty"`
}

// RealmRepresentation defines model for RealmRepresentation.
type RealmRepresentation struct {
	AccessCodeLifespan                                        *int32                                  `json:"accessCodeLifespan,omitempty"`
	AccessCodeLifespanLogin                                   *int32                                  `json:"accessCodeLifespanLogin,omitempty"`
	AccessCodeLifespanUserAction                              *int32                                  `json:"accessCodeLifespanUserAction,omitempty"`
	AccessTokenLifespan                                       *int32                                  `json:"accessTokenLifespan,omitempty"`
	AccessTokenLifespanForImplicitFlow                        *int32                                  `json:"accessTokenLifespanForImplicitFlow,omitempty"`
	AccountTheme                                              *string                                 `json:"accountTheme,omitempty"`
	ActionTokenGeneratedByAdminLifespan                       *int32                                  `json:"actionTokenGeneratedByAdminLifespan,omitempty"`
	ActionTokenGeneratedByUserLifespan                        *int32                                  `json:"actionTokenGeneratedByUserLifespan,omitempty"`
	AdminEventsDetailsEnabled                                 *bool                                   `json:"adminEventsDetailsEnabled,omitempty"`
	AdminEventsEnabled                                        *bool                                   `json:"adminEventsEnabled,omitempty"`
	AdminTheme                                                *string                                 `json:"adminTheme,omitempty"`
	Attributes                                                *map[string]interface{}                 `json:"attributes,omitempty"`
	AuthenticationFlows                                       *[]AuthenticationFlowRepresentation     `json:"authenticationFlows,omitempty"`
	AuthenticatorConfig                                       *[]AuthenticatorConfigRepresentation    `json:"authenticatorConfig,omitempty"`
	BrowserFlow                                               *string                                 `json:"browserFlow,omitempty"`
	BrowserSecurityHeaders                                    *map[string]interface{}                 `json:"browserSecurityHeaders,omitempty"`
	BruteForceProtected                                       *bool                                   `json:"bruteForceProtected,omitempty"`
	ClientAuthenticationFlow                                  *string                                 `json:"clientAuthenticationFlow,omitempty"`
	ClientScopeMappings                                       *map[string]interface{}                 `json:"clientScopeMappings,omitempty"`
	ClientScopes                                              *[]ClientScopeRepresentation            `json:"clientScopes,omitempty"`
	Clients                                                   *[]ClientRepresentation                 `json:"clients,omitempty"`
	Components                                                *MultivaluedHashMap                     `json:"components,omitempty"`
	DefaultDefaultClientScopes                                *[]string                               `json:"defaultDefaultClientScopes,omitempty"`
	DefaultGroups                                             *[]string                               `json:"defaultGroups,omitempty"`
	DefaultLocale                                             *string                                 `json:"defaultLocale,omitempty"`
	DefaultOptionalClientScopes                               *[]string                               `json:"defaultOptionalClientScopes,omitempty"`
	DefaultRoles                                              *[]string                               `json:"defaultRoles,omitempty"`
	DefaultSignatureAlgorithm                                 *string                                 `json:"defaultSignatureAlgorithm,omitempty"`
	DirectGrantFlow                                           *string                                 `json:"directGrantFlow,omitempty"`
	DisplayName                                               *string                                 `json:"displayName,omitempty"`
	DisplayNameHtml                                           *string                                 `json:"displayNameHtml,omitempty"`
	DockerAuthenticationFlow                                  *string                                 `json:"dockerAuthenticationFlow,omitempty"`
	DuplicateEmailsAllowed                                    *bool                                   `json:"duplicateEmailsAllowed,omitempty"`
	EditUsernameAllowed                                       *bool                                   `json:"editUsernameAllowed,omitempty"`
	EmailTheme                                                *string                                 `json:"emailTheme,omitempty"`
	Enabled                                                   *bool                                   `json:"enabled,omitempty"`
	EnabledEventTypes                                         *[]string                               `json:"enabledEventTypes,omitempty"`
	EventsEnabled                                             *bool                                   `json:"eventsEnabled,omitempty"`
	EventsExpiration                                          *int64                                  `json:"eventsExpiration,omitempty"`
	EventsListeners                                           *[]string                               `json:"eventsListeners,omitempty"`
	FailureFactor                                             *int32                                  `json:"failureFactor,omitempty"`
	FederatedUsers                                            *[]UserRepresentation                   `json:"federatedUsers,omitempty"`
	Groups                                                    *[]GroupRepresentation                  `json:"groups,omitempty"`
	Id                                                        *string                                 `json:"id,omitempty"`
	IdentityProviderMappers                                   *[]IdentityProviderMapperRepresentation `json:"identityProviderMappers,omitempty"`
	IdentityProviders                                         *[]IdentityProviderRepresentation       `json:"identityProviders,omitempty"`
	InternationalizationEnabled                               *bool                                   `json:"internationalizationEnabled,omitempty"`
	KeycloakVersion                                           *string                                 `json:"keycloakVersion,omitempty"`
	LoginTheme                                                *string                                 `json:"loginTheme,omitempty"`
	LoginWithEmailAllowed                                     *bool                                   `json:"loginWithEmailAllowed,omitempty"`
	MaxDeltaTimeSeconds                                       *int32                                  `json:"maxDeltaTimeSeconds,omitempty"`
	MaxFailureWaitSeconds                                     *int32                                  `json:"maxFailureWaitSeconds,omitempty"`
	MinimumQuickLoginWaitSeconds                              *int32                                  `json:"minimumQuickLoginWaitSeconds,omitempty"`
	NotBefore                                                 *int32                                  `json:"notBefore,omitempty"`
	OfflineSessionIdleTimeout                                 *int32                                  `json:"offlineSessionIdleTimeout,omitempty"`
	OfflineSessionMaxLifespan                                 *int32                                  `json:"offlineSessionMaxLifespan,omitempty"`
	OfflineSessionMaxLifespanEnabled                          *bool                                   `json:"offlineSessionMaxLifespanEnabled,omitempty"`
	OtpPolicyAlgorithm                                        *string                                 `json:"otpPolicyAlgorithm,omitempty"`
	OtpPolicyDigits                                           *int32                                  `json:"otpPolicyDigits,omitempty"`
	OtpPolicyInitialCounter                                   *int32                                  `json:"otpPolicyInitialCounter,omitempty"`
	OtpPolicyLookAheadWindow                                  *int32                                  `json:"otpPolicyLookAheadWindow,omitempty"`
	OtpPolicyPeriod                                           *int32                                  `json:"otpPolicyPeriod,omitempty"`
	OtpPolicyType                                             *string                                 `json:"otpPolicyType,omitempty"`
	OtpSupportedApplications                                  *[]string                               `json:"otpSupportedApplications,omitempty"`
	PasswordPolicy                                            *string                                 `json:"passwordPolicy,omitempty"`
	PermanentLockout                                          *bool                                   `json:"permanentLockout,omitempty"`
	ProtocolMappers                                           *[]ProtocolMapperRepresentation         `json:"protocolMappers,omitempty"`
	QuickLoginCheckMilliSeconds                               *int64                                  `json:"quickLoginCheckMilliSeconds,omitempty"`
	Realm                                                     *string                                 `json:"realm,omitempty"`
	RefreshTokenMaxReuse                                      *int32                                  `json:"refreshTokenMaxReuse,omitempty"`
	RegistrationAllowed                                       *bool                                   `json:"registrationAllowed,omitempty"`
	RegistrationEmailAsUsername                               *bool                                   `json:"registrationEmailAsUsername,omitempty"`
	RegistrationFlow                                          *string                                 `json:"registrationFlow,omitempty"`
	RememberMe                                                *bool                                   `json:"rememberMe,omitempty"`
	RequiredActions                                           *[]RequiredActionProviderRepresentation `json:"requiredActions,omitempty"`
	ResetCredentialsFlow                                      *string                                 `json:"resetCredentialsFlow,omitempty"`
	ResetPasswordAllowed                                      *bool                                   `json:"resetPasswordAllowed,omitempty"`
	RevokeRefreshToken                                        *bool                                   `json:"revokeRefreshToken,omitempty"`
	Roles                                                     *RolesRepresentation                    `json:"roles,omitempty"`
	ScopeMappings                                             *[]ScopeMappingRepresentation           `json:"scopeMappings,omitempty"`
	SmtpServer                                                *map[string]interface{}                 `json:"smtpServer,omitempty"`
	SslRequired                                               *string                                 `json:"sslRequired,omitempty"`
	SsoSessionIdleTimeout                                     *int32                                  `json:"ssoSessionIdleTimeout,omitempty"`
	SsoSessionIdleTimeoutRememberMe                           *int32                                  `json:"ssoSessionIdleTimeoutRememberMe,omitempty"`
	SsoSessionMaxLifespan                                     *int32                                  `json:"ssoSessionMaxLifespan,omitempty"`
	SsoSessionMaxLifespanRememberMe                           *int32                                  `json:"ssoSessionMaxLifespanRememberMe,omitempty"`
	SupportedLocales                                          *[]string                               `json:"supportedLocales,omitempty"`
	UserFederationMappers                                     *[]UserFederationMapperRepresentation   `json:"userFederationMappers,omitempty"`
	UserFederationProviders                                   *[]UserFederationProviderRepresentation `json:"userFederationProviders,omitempty"`
	UserManagedAccessAllowed                                  *bool                                   `json:"userManagedAccessAllowed,omitempty"`
	Users                                                     *[]UserRepresentation                   `json:"users,omitempty"`
	VerifyEmail                                               *bool                                   `json:"verifyEmail,omitempty"`
	WaitIncrementSeconds                                      *int32                                  `json:"waitIncrementSeconds,omitempty"`
	WebAuthnPolicyAcceptableAaguids                           *[]string                               `json:"webAuthnPolicyAcceptableAaguids,omitempty"`
	WebAuthnPolicyAttestationConveyancePreference             *string                                 `json:"webAuthnPolicyAttestationConveyancePreference,omitempty"`
	WebAuthnPolicyAuthenticatorAttachment                     *string                                 `json:"webAuthnPolicyAuthenticatorAttachment,omitempty"`
	WebAuthnPolicyAvoidSameAuthenticatorRegister              *bool                                   `json:"webAuthnPolicyAvoidSameAuthenticatorRegister,omitempty"`
	WebAuthnPolicyCreateTimeout                               *int32                                  `json:"webAuthnPolicyCreateTimeout,omitempty"`
	WebAuthnPolicyPasswordlessAcceptableAaguids               *[]string                               `json:"webAuthnPolicyPasswordlessAcceptableAaguids,omitempty"`
	WebAuthnPolicyPasswordlessAttestationConveyancePreference *string                                 `json:"webAuthnPolicyPasswordlessAttestationConveyancePreference,omitempty"`
	WebAuthnPolicyPasswordlessAuthenticatorAttachment         *string                                 `json:"webAuthnPolicyPasswordlessAuthenticatorAttachment,omitempty"`
	WebAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister  *bool                                   `json:"webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister,omitempty"`
	WebAuthnPolicyPasswordlessCreateTimeout                   *int32                                  `json:"webAuthnPolicyPasswordlessCreateTimeout,omitempty"`
	WebAuthnPolicyPasswordlessRequireResidentKey              *string                                 `json:"webAuthnPolicyPasswordlessRequireResidentKey,omitempty"`
	WebAuthnPolicyPasswordlessRpEntityName                    *string                                 `json:"webAuthnPolicyPasswordlessRpEntityName,omitempty"`
	WebAuthnPolicyPasswordlessRpId                            *string                                 `json:"webAuthnPolicyPasswordlessRpId,omitempty"`
	WebAuthnPolicyPasswordlessSignatureAlgorithms             *[]string                               `json:"webAuthnPolicyPasswordlessSignatureAlgorithms,omitempty"`
	WebAuthnPolicyPasswordlessUserVerificationRequirement     *string                                 `json:"webAuthnPolicyPasswordlessUserVerificationRequirement,omitempty"`
	WebAuthnPolicyRequireResidentKey                          *string                                 `json:"webAuthnPolicyRequireResidentKey,omitempty"`
	WebAuthnPolicyRpEntityName                                *string                                 `json:"webAuthnPolicyRpEntityName,omitempty"`
	WebAuthnPolicyRpId                                        *string                                 `json:"webAuthnPolicyRpId,omitempty"`
	WebAuthnPolicySignatureAlgorithms                         *[]string                               `json:"webAuthnPolicySignatureAlgorithms,omitempty"`
	WebAuthnPolicyUserVerificationRequirement                 *string                                 `json:"webAuthnPolicyUserVerificationRequirement,omitempty"`
}

// RequiredActionProviderRepresentation defines model for RequiredActionProviderRepresentation.
type RequiredActionProviderRepresentation struct {
	Alias         *string                 `json:"alias,omitempty"`
	Config        *map[string]interface{} `json:"config,omitempty"`
	DefaultAction *bool                   `json:"defaultAction,omitempty"`
	Enabled       *bool                   `json:"enabled,omitempty"`
	Name          *string                 `json:"name,omitempty"`
	Priority      *int32                  `json:"priority,omitempty"`
	ProviderId    *string                 `json:"providerId,omitempty"`
}

// ResourceRepresentation defines model for ResourceRepresentation.
type ResourceRepresentation struct {
	Attributes         *map[string]interface{} `json:"attributes,omitempty"`
	DisplayName        *string                 `json:"displayName,omitempty"`
	IconUri            *string                 `json:"icon_uri,omitempty"`
	Id                 *string                 `json:"id,omitempty"`
	Name               *string                 `json:"name,omitempty"`
	OwnerManagedAccess *bool                   `json:"ownerManagedAccess,omitempty"`
	Scopes             *[]ScopeRepresentation  `json:"scopes,omitempty"`
	Type               *string                 `json:"type,omitempty"`
	Uris               *[]string               `json:"uris,omitempty"`
}

// ResourceServerRepresentation defines model for ResourceServerRepresentation.
type ResourceServerRepresentation struct {
	AllowRemoteResourceManagement *bool                                              `json:"allowRemoteResourceManagement,omitempty"`
	ClientId                      *string                                            `json:"clientId,omitempty"`
	DecisionStrategy              *ResourceServerRepresentationDecisionStrategy      `json:"decisionStrategy,omitempty"`
	Id                            *string                                            `json:"id,omitempty"`
	Name                          *string                                            `json:"name,omitempty"`
	Policies                      *[]PolicyRepresentation                            `json:"policies,omitempty"`
	PolicyEnforcementMode         *ResourceServerRepresentationPolicyEnforcementMode `json:"policyEnforcementMode,omitempty"`
	Resources                     *[]ResourceRepresentation                          `json:"resources,omitempty"`
	Scopes                        *[]ScopeRepresentation                             `json:"scopes,omitempty"`
}

// ResourceServerRepresentationDecisionStrategy defines model for ResourceServerRepresentation.DecisionStrategy.
type ResourceServerRepresentationDecisionStrategy string

// ResourceServerRepresentationPolicyEnforcementMode defines model for ResourceServerRepresentation.PolicyEnforcementMode.
type ResourceServerRepresentationPolicyEnforcementMode string

// RoleRepresentation defines model for RoleRepresentation.
type RoleRepresentation struct {
	Attributes  *map[string]interface{}       `json:"attributes,omitempty"`
	ClientRole  *bool                         `json:"clientRole,omitempty"`
	Composite   *bool                         `json:"composite,omitempty"`
	Composites  *RoleRepresentationComposites `json:"composites,omitempty"`
	ContainerId *string                       `json:"containerId,omitempty"`
	Description *string                       `json:"description,omitempty"`
	Id          *string                       `json:"id,omitempty"`
	Name        *string                       `json:"name,omitempty"`
}

// RoleRepresentationComposites defines model for RoleRepresentation-Composites.
type RoleRepresentationComposites struct {
	Client *map[string]interface{} `json:"client,omitempty"`
	Realm  *[]string               `json:"realm,omitempty"`
}

// RolesRepresentation defines model for RolesRepresentation.
type RolesRepresentation struct {
	Client *map[string]interface{} `json:"client,omitempty"`
	Realm  *[]RoleRepresentation   `json:"realm,omitempty"`
}

// ScopeMappingRepresentation defines model for ScopeMappingRepresentation.
type ScopeMappingRepresentation struct {
	Client      *string   `json:"client,omitempty"`
	ClientScope *string   `json:"clientScope,omitempty"`
	Roles       *[]string `json:"roles,omitempty"`
	Self        *string   `json:"self,omitempty"`
}

// ScopeRepresentation defines model for ScopeRepresentation.
type ScopeRepresentation struct {
	DisplayName *string                   `json:"displayName,omitempty"`
	IconUri     *string                   `json:"iconUri,omitempty"`
	Id          *string                   `json:"id,omitempty"`
	Name        *string                   `json:"name,omitempty"`
	Policies    *[]PolicyRepresentation   `json:"policies,omitempty"`
	Resources   *[]ResourceRepresentation `json:"resources,omitempty"`
}

// ServerInfoRepresentation defines model for ServerInfoRepresentation.
type ServerInfoRepresentation struct {
	BuiltinProtocolMappers *map[string]interface{}             `json:"builtinProtocolMappers,omitempty"`
	ClientImporters        *[]map[string]interface{}           `json:"clientImporters,omitempty"`
	ClientInstallations    *map[string]interface{}             `json:"clientInstallations,omitempty"`
	ComponentTypes         *map[string]interface{}             `json:"componentTypes,omitempty"`
	Enums                  *map[string]interface{}             `json:"enums,omitempty"`
	IdentityProviders      *[]map[string]interface{}           `json:"identityProviders,omitempty"`
	MemoryInfo             *MemoryInfoRepresentation           `json:"memoryInfo,omitempty"`
	PasswordPolicies       *[]PasswordPolicyTypeRepresentation `json:"passwordPolicies,omitempty"`
	ProfileInfo            *ProfileInfoRepresentation          `json:"profileInfo,omitempty"`
	ProtocolMapperTypes    *map[string]interface{}             `json:"protocolMapperTypes,omitempty"`
	Providers              *map[string]interface{}             `json:"providers,omitempty"`
	SocialProviders        *[]map[string]interface{}           `json:"socialProviders,omitempty"`
	SystemInfo             *SystemInfoRepresentation           `json:"systemInfo,omitempty"`
	Themes                 *map[string]interface{}             `json:"themes,omitempty"`
}

// SynchronizationResult defines model for SynchronizationResult.
type SynchronizationResult struct {
	Added   *int32  `json:"added,omitempty"`
	Failed  *int32  `json:"failed,omitempty"`
	Ignored *bool   `json:"ignored,omitempty"`
	Removed *int32  `json:"removed,omitempty"`
	Status  *string `json:"status,omitempty"`
	Updated *int32  `json:"updated,omitempty"`
}

// SystemInfoRepresentation defines model for SystemInfoRepresentation.
type SystemInfoRepresentation struct {
	FileEncoding   *string `json:"fileEncoding,omitempty"`
	JavaHome       *string `json:"javaHome,omitempty"`
	JavaRuntime    *string `json:"javaRuntime,omitempty"`
	JavaVendor     *string `json:"javaVendor,omitempty"`
	JavaVersion    *string `json:"javaVersion,omitempty"`
	JavaVm         *string `json:"javaVm,omitempty"`
	JavaVmVersion  *string `json:"javaVmVersion,omitempty"`
	OsArchitecture *string `json:"osArchitecture,omitempty"`
	OsName         *string `json:"osName,omitempty"`
	OsVersion      *string `json:"osVersion,omitempty"`
	ServerTime     *string `json:"serverTime,omitempty"`
	Uptime         *string `json:"uptime,omitempty"`
	UptimeMillis   *int64  `json:"uptimeMillis,omitempty"`
	UserDir        *string `json:"userDir,omitempty"`
	UserLocale     *string `json:"userLocale,omitempty"`
	UserName       *string `json:"userName,omitempty"`
	UserTimezone   *string `json:"userTimezone,omitempty"`
	Version        *string `json:"version,omitempty"`
}

// TestLdapConnectionRepresentation defines model for TestLdapConnectionRepresentation.
type TestLdapConnectionRepresentation struct {
	Action            *string `json:"action,omitempty"`
	BindCredential    *string `json:"bindCredential,omitempty"`
	BindDn            *string `json:"bindDn,omitempty"`
	ComponentId       *string `json:"componentId,omitempty"`
	ConnectionTimeout *string `json:"connectionTimeout,omitempty"`
	ConnectionUrl     *string `json:"connectionUrl,omitempty"`
	StartTls          *string `json:"startTls,omitempty"`
	UseTruststoreSpi  *string `json:"useTruststoreSpi,omitempty"`
}

// UserConsentRepresentation defines model for UserConsentRepresentation.
type UserConsentRepresentation struct {
	ClientId            *string   `json:"clientId,omitempty"`
	CreatedDate         *int64    `json:"createdDate,omitempty"`
	GrantedClientScopes *[]string `json:"grantedClientScopes,omitempty"`
	LastUpdatedDate     *int64    `json:"lastUpdatedDate,omitempty"`
}

// UserFederationMapperRepresentation defines model for UserFederationMapperRepresentation.
type UserFederationMapperRepresentation struct {
	Config                        *map[string]interface{} `json:"config,omitempty"`
	FederationMapperType          *string                 `json:"federationMapperType,omitempty"`
	FederationProviderDisplayName *string                 `json:"federationProviderDisplayName,omitempty"`
	Id                            *string                 `json:"id,omitempty"`
	Name                          *string                 `json:"name,omitempty"`
}

// UserFederationProviderRepresentation defines model for UserFederationProviderRepresentation.
type UserFederationProviderRepresentation struct {
	ChangedSyncPeriod *int32                  `json:"changedSyncPeriod,omitempty"`
	Config            *map[string]interface{} `json:"config,omitempty"`
	DisplayName       *string                 `json:"displayName,omitempty"`
	FullSyncPeriod    *int32                  `json:"fullSyncPeriod,omitempty"`
	Id                *string                 `json:"id,omitempty"`
	LastSync          *int32                  `json:"lastSync,omitempty"`
	Priority          *int32                  `json:"priority,omitempty"`
	ProviderName      *string                 `json:"providerName,omitempty"`
}

// UserRepresentation defines model for UserRepresentation.
type UserRepresentation struct {
	Access                     *map[string]interface{}            `json:"access,omitempty"`
	Attributes                 *map[string]interface{}            `json:"attributes,omitempty"`
	ClientConsents             *[]UserConsentRepresentation       `json:"clientConsents,omitempty"`
	ClientRoles                *map[string]interface{}            `json:"clientRoles,omitempty"`
	CreatedTimestamp           *int64                             `json:"createdTimestamp,omitempty"`
	Credentials                *[]CredentialRepresentation        `json:"credentials,omitempty"`
	DisableableCredentialTypes *[]string                          `json:"disableableCredentialTypes,omitempty"`
	Email                      *string                            `json:"email,omitempty"`
	EmailVerified              *bool                              `json:"emailVerified,omitempty"`
	Enabled                    *bool                              `json:"enabled,omitempty"`
	FederatedIdentities        *[]FederatedIdentityRepresentation `json:"federatedIdentities,omitempty"`
	FederationLink             *string                            `json:"federationLink,omitempty"`
	FirstName                  *string                            `json:"firstName,omitempty"`
	Groups                     *[]string                          `json:"groups,omitempty"`
	Id                         *string                            `json:"id,omitempty"`
	LastName                   *string                            `json:"lastName,omitempty"`
	NotBefore                  *int32                             `json:"notBefore,omitempty"`
	Origin                     *string                            `json:"origin,omitempty"`
	RealmRoles                 *[]string                          `json:"realmRoles,omitempty"`
	RequiredActions            *[]string                          `json:"requiredActions,omitempty"`
	Self                       *string                            `json:"self,omitempty"`
	ServiceAccountClientId     *string                            `json:"serviceAccountClientId,omitempty"`
	Username                   *string                            `json:"username,omitempty"`
}

// UserSessionRepresentation defines model for UserSessionRepresentation.
type UserSessionRepresentation struct {
	Clients    *map[string]interface{} `json:"clients,omitempty"`
	Id         *string                 `json:"id,omitempty"`
	IpAddress  *string                 `json:"ipAddress,omitempty"`
	LastAccess *int64                  `json:"lastAccess,omitempty"`
	Start      *int64                  `json:"start,omitempty"`
	UserId     *string                 `json:"userId,omitempty"`
	Username   *string                 `json:"username,omitempty"`
}

// GetRealmAdminEventsParams defines parameters for GetRealmAdminEvents.
type GetRealmAdminEventsParams struct {
	AuthClient    *string `form:"authClient,omitempty" json:"authClient,omitempty"`
	AuthIpAddress *string `form:"authIpAddress,omitempty" json:"authIpAddress,omitempty"`
	AuthRealm     *string `form:"authRealm,omitempty" json:"authRealm,omitempty"`

	// AuthUser user id
	AuthUser *string `form:"authUser,omitempty" json:"authUser,omitempty"`
	DateFrom *string `form:"dateFrom,omitempty" json:"dateFrom,omitempty"`
	DateTo   *string `form:"dateTo,omitempty" json:"dateTo,omitempty"`
	First    *int32  `form:"first,omitempty" json:"first,omitempty"`

	// Max Maximum results size (defaults to 100)
	Max            *int32    `form:"max,omitempty" json:"max,omitempty"`
	OperationTypes *[]string `form:"operationTypes,omitempty" json:"operationTypes,omitempty"`
	ResourcePath   *string   `form:"resourcePath,omitempty" json:"resourcePath,omitempty"`
	ResourceTypes  *[]string `form:"resourceTypes,omitempty" json:"resourceTypes,omitempty"`
}

// PostRealmAuthenticationFlowsFlowAliasCopyJSONBody defines parameters for PostRealmAuthenticationFlowsFlowAliasCopy.
type PostRealmAuthenticationFlowsFlowAliasCopyJSONBody map[string]interface{}

// PostRealmAuthenticationFlowsFlowAliasExecutionsExecutionJSONBody defines parameters for PostRealmAuthenticationFlowsFlowAliasExecutionsExecution.
type PostRealmAuthenticationFlowsFlowAliasExecutionsExecutionJSONBody map[string]interface{}

// PostRealmAuthenticationFlowsFlowAliasExecutionsFlowJSONBody defines parameters for PostRealmAuthenticationFlowsFlowAliasExecutionsFlow.
type PostRealmAuthenticationFlowsFlowAliasExecutionsFlowJSONBody map[string]interface{}

// PostRealmAuthenticationRegisterRequiredActionJSONBody defines parameters for PostRealmAuthenticationRegisterRequiredAction.
type PostRealmAuthenticationRegisterRequiredActionJSONBody map[string]interface{}

// PostRealmClientDescriptionConverterTextBody defines parameters for PostRealmClientDescriptionConverter.
type PostRealmClientDescriptionConverterTextBody = string

// PostRealmClientScopesIdProtocolMappersAddModelsJSONBody defines parameters for PostRealmClientScopesIdProtocolMappersAddModels.
type PostRealmClientScopesIdProtocolMappersAddModelsJSONBody = []ProtocolMapperRepresentation

// DeleteRealmClientScopesIdScopeMappingsClientsClientJSONBody defines parameters for DeleteRealmClientScopesIdScopeMappingsClientsClient.
type DeleteRealmClientScopesIdScopeMappingsClientsClientJSONBody = []RoleRepresentation

// PostRealmClientScopesIdScopeMappingsClientsClientJSONBody defines parameters for PostRealmClientScopesIdScopeMappingsClientsClient.
type PostRealmClientScopesIdScopeMappingsClientsClientJSONBody = []RoleRepresentation

// DeleteRealmClientScopesIdScopeMappingsRealmJSONBody defines parameters for DeleteRealmClientScopesIdScopeMappingsRealm.
type DeleteRealmClientScopesIdScopeMappingsRealmJSONBody = []RoleRepresentation

// PostRealmClientScopesIdScopeMappingsRealmJSONBody defines parameters for PostRealmClientScopesIdScopeMappingsRealm.
type PostRealmClientScopesIdScopeMappingsRealmJSONBody = []RoleRepresentation

// GetRealmClientsParams defines parameters for GetRealmClients.
type GetRealmClientsParams struct {
	// ClientId filter by clientId
	ClientId *string `form:"clientId,omitempty" json:"clientId,omitempty"`

	// First the first result
	First *int32 `form:"first,omitempty" json:"first,omitempty"`

	// Max the max results to return
	Max *int32 `form:"max,omitempty" json:"max,omitempty"`

	// Search whether this is a search query or a getClientById query
	Search *bool `form:"search,omitempty" json:"search,omitempty"`

	// ViewableOnly filter clients that cannot be viewed in full by admin
	ViewableOnly *bool `form:"viewableOnly,omitempty" json:"viewableOnly,omitempty"`
}

// GetRealmClientsIdEvaluateScopesGenerateExampleAccessTokenParams defines parameters for GetRealmClientsIdEvaluateScopesGenerateExampleAccessToken.
type GetRealmClientsIdEvaluateScopesGenerateExampleAccessTokenParams struct {
	Scope  *string `form:"scope,omitempty" json:"scope,omitempty"`
	UserId *string `form:"userId,omitempty" json:"userId,omitempty"`
}

// GetRealmClientsIdEvaluateScopesProtocolMappersParams defines parameters for GetRealmClientsIdEvaluateScopesProtocolMappers.
type GetRealmClientsIdEvaluateScopesProtocolMappersParams struct {
	Scope *string `form:"scope,omitempty" json:"scope,omitempty"`
}

// GetRealmClientsIdEvaluateScopesScopeMappingsRoleContainerIdGrantedParams defines parameters for GetRealmClientsIdEvaluateScopesScopeMappingsRoleContainerIdGranted.
type GetRealmClientsIdEvaluateScopesScopeMappingsRoleContainerIdGrantedParams struct {
	Scope *string `form:"scope,omitempty" json:"scope,omitempty"`
}

// GetRealmClientsIdEvaluateScopesScopeMappingsRoleContainerIdNotGrantedParams defines parameters for GetRealmClientsIdEvaluateScopesScopeMappingsRoleContainerIdNotGranted.
type GetRealmClientsIdEvaluateScopesScopeMappingsRoleContainerIdNotGrantedParams struct {
	Scope *string `form:"scope,omitempty" json:"scope,omitempty"`
}

// PostRealmClientsIdNodesJSONBody defines parameters for PostRealmClientsIdNodes.
type PostRealmClientsIdNodesJSONBody map[string]interface{}

// GetRealmClientsIdOfflineSessionsParams defines parameters for GetRealmClientsIdOfflineSessions.
type GetRealmClientsIdOfflineSessionsParams struct {
	// First Paging offset
	First *int32 `form:"first,omitempty" json:"first,omitempty"`

	// Max Maximum results size (defaults to 100)
	Max *int32 `form:"max,omitempty" json:"max,omitempty"`
}

// PostRealmClientsIdProtocolMappersAddModelsJSONBody defines parameters for PostRealmClientsIdProtocolMappersAddModels.
type PostRealmClientsIdProtocolMappersAddModelsJSONBody = []ProtocolMapperRepresentation

// GetRealmClientsIdRolesParams defines parameters for GetRealmClientsIdRoles.
type GetRealmClientsIdRolesParams struct {
	BriefRepresentation *bool   `form:"briefRepresentation,omitempty" json:"briefRepresentation,omitempty"`
	First               *int32  `form:"first,omitempty" json:"first,omitempty"`
	Max                 *int32  `form:"max,omitempty" json:"max,omitempty"`
	Search              *string `form:"search,omitempty" json:"search,omitempty"`
}

// DeleteRealmClientsIdRolesRoleNameCompositesJSONBody defines parameters for DeleteRealmClientsIdRolesRoleNameComposites.
type DeleteRealmClientsIdRolesRoleNameCompositesJSONBody = []RoleRepresentation

// PostRealmClientsIdRolesRoleNameCompositesJSONBody defines parameters for PostRealmClientsIdRolesRoleNameComposites.
type PostRealmClientsIdRolesRoleNameCompositesJSONBody = []RoleRepresentation

// GetRealmClientsIdRolesRoleNameGroupsParams defines parameters for GetRealmClientsIdRolesRoleNameGroups.
type GetRealmClientsIdRolesRoleNameGroupsParams struct {
	// BriefRepresentation if false, return a full representation of the GroupRepresentation objects
	BriefRepresentation *bool  `form:"briefRepresentation,omitempty" json:"briefRepresentation,omitempty"`
	First               *int32 `form:"first,omitempty" json:"first,omitempty"`
	Max                 *int32 `form:"max,omitempty" json:"max,omitempty"`
}

// GetRealmClientsIdRolesRoleNameUsersParams defines parameters for GetRealmClientsIdRolesRoleNameUsers.
type GetRealmClientsIdRolesRoleNameUsersParams struct {
	First *int32 `form:"first,omitempty" json:"first,omitempty"`
	Max   *int32 `form:"max,omitempty" json:"max,omitempty"`
}

// DeleteRealmClientsIdScopeMappingsClientsClientJSONBody defines parameters for DeleteRealmClientsIdScopeMappingsClientsClient.
type DeleteRealmClientsIdScopeMappingsClientsClientJSONBody = []RoleRepresentation

// PostRealmClientsIdScopeMappingsClientsClientJSONBody defines parameters for PostRealmClientsIdScopeMappingsClientsClient.
type PostRealmClientsIdScopeMappingsClientsClientJSONBody = []RoleRepresentation

// DeleteRealmClientsIdScopeMappingsRealmJSONBody defines parameters for DeleteRealmClientsIdScopeMappingsRealm.
type DeleteRealmClientsIdScopeMappingsRealmJSONBody = []RoleRepresentation

// PostRealmClientsIdScopeMappingsRealmJSONBody defines parameters for PostRealmClientsIdScopeMappingsRealm.
type PostRealmClientsIdScopeMappingsRealmJSONBody = []RoleRepresentation

// GetRealmClientsIdUserSessionsParams defines parameters for GetRealmClientsIdUserSessions.
type GetRealmClientsIdUserSessionsParams struct {
	// First Paging offset
	First *int32 `form:"first,omitempty" json:"first,omitempty"`

	// Max Maximum results size (defaults to 100)
	Max *int32 `form:"max,omitempty" json:"max,omitempty"`
}

// GetRealmComponentsParams defines parameters for GetRealmComponents.
type GetRealmComponentsParams struct {
	Name   *string `form:"name,omitempty" json:"name,omitempty"`
	Parent *string `form:"parent,omitempty" json:"parent,omitempty"`
	Type   *string `form:"type,omitempty" json:"type,omitempty"`
}

// GetRealmComponentsIdSubComponentTypesParams defines parameters for GetRealmComponentsIdSubComponentTypes.
type GetRealmComponentsIdSubComponentTypesParams struct {
	Type *string `form:"type,omitempty" json:"type,omitempty"`
}

// GetRealmEventsParams defines parameters for GetRealmEvents.
type GetRealmEventsParams struct {
	// Client App or oauth client name
	Client *string `form:"client,omitempty" json:"client,omitempty"`

	// DateFrom From date
	DateFrom *string `form:"dateFrom,omitempty" json:"dateFrom,omitempty"`

	// DateTo To date
	DateTo *string `form:"dateTo,omitempty" json:"dateTo,omitempty"`

	// First Paging offset
	First *int32 `form:"first,omitempty" json:"first,omitempty"`

	// IpAddress IP address
	IpAddress *string `form:"ipAddress,omitempty" json:"ipAddress,omitempty"`

	// Max Maximum results size (defaults to 100)
	Max *int32 `form:"max,omitempty" json:"max,omitempty"`

	// Type The types of events to return
	Type *[]string `form:"type,omitempty" json:"type,omitempty"`

	// User User id
	User *string `form:"user,omitempty" json:"user,omitempty"`
}

// GetRealmGroupsParams defines parameters for GetRealmGroups.
type GetRealmGroupsParams struct {
	BriefRepresentation *bool   `form:"briefRepresentation,omitempty" json:"briefRepresentation,omitempty"`
	First               *int32  `form:"first,omitempty" json:"first,omitempty"`
	Max                 *int32  `form:"max,omitempty" json:"max,omitempty"`
	Search              *string `form:"search,omitempty" json:"search,omitempty"`
}

// GetRealmGroupsCountParams defines parameters for GetRealmGroupsCount.
type GetRealmGroupsCountParams struct {
	Search *string `form:"search,omitempty" json:"search,omitempty"`
	Top    *bool   `form:"top,omitempty" json:"top,omitempty"`
}

// GetRealmGroupsIdMembersParams defines parameters for GetRealmGroupsIdMembers.
type GetRealmGroupsIdMembersParams struct {
	// BriefRepresentation Only return basic information (only guaranteed to return id, username, created, first and last name,
	//  email, enabled state, email verification state, federation link, and access.
	//  Note that it means that namely user attributes, required actions, and not before are not returned.)
	BriefRepresentation *bool `form:"briefRepresentation,omitempty" json:"briefRepresentation,omitempty"`

	// First Pagination offset
	First *int32 `form:"first,omitempty" json:"first,omitempty"`

	// Max Maximum results size (defaults to 100)
	Max *int32 `form:"max,omitempty" json:"max,omitempty"`
}

// DeleteRealmGroupsIdRoleMappingsClientsClientJSONBody defines parameters for DeleteRealmGroupsIdRoleMappingsClientsClient.
type DeleteRealmGroupsIdRoleMappingsClientsClientJSONBody = []RoleRepresentation

// PostRealmGroupsIdRoleMappingsClientsClientJSONBody defines parameters for PostRealmGroupsIdRoleMappingsClientsClient.
type PostRealmGroupsIdRoleMappingsClientsClientJSONBody = []RoleRepresentation

// DeleteRealmGroupsIdRoleMappingsRealmJSONBody defines parameters for DeleteRealmGroupsIdRoleMappingsRealm.
type DeleteRealmGroupsIdRoleMappingsRealmJSONBody = []RoleRepresentation

// PostRealmGroupsIdRoleMappingsRealmJSONBody defines parameters for PostRealmGroupsIdRoleMappingsRealm.
type PostRealmGroupsIdRoleMappingsRealmJSONBody = []RoleRepresentation

// GetRealmIdentityProviderInstancesAliasExportParams defines parameters for GetRealmIdentityProviderInstancesAliasExport.
type GetRealmIdentityProviderInstancesAliasExportParams struct {
	// Format Format to use
	Format *string `form:"format,omitempty" json:"format,omitempty"`
}

// PostRealmPartialExportParams defines parameters for PostRealmPartialExport.
type PostRealmPartialExportParams struct {
	ExportClients        *bool `form:"exportClients,omitempty" json:"exportClients,omitempty"`
	ExportGroupsAndRoles *bool `form:"exportGroupsAndRoles,omitempty" json:"exportGroupsAndRoles,omitempty"`
}

// GetRealmRolesParams defines parameters for GetRealmRoles.
type GetRealmRolesParams struct {
	BriefRepresentation *bool   `form:"briefRepresentation,omitempty" json:"briefRepresentation,omitempty"`
	First               *int32  `form:"first,omitempty" json:"first,omitempty"`
	Max                 *int32  `form:"max,omitempty" json:"max,omitempty"`
	Search              *string `form:"search,omitempty" json:"search,omitempty"`
}

// DeleteRealmRolesByIdRoleIdCompositesJSONBody defines parameters for DeleteRealmRolesByIdRoleIdComposites.
type DeleteRealmRolesByIdRoleIdCompositesJSONBody = []RoleRepresentation

// PostRealmRolesByIdRoleIdCompositesJSONBody defines parameters for PostRealmRolesByIdRoleIdComposites.
type PostRealmRolesByIdRoleIdCompositesJSONBody = []RoleRepresentation

// DeleteRealmRolesRoleNameCompositesJSONBody defines parameters for DeleteRealmRolesRoleNameComposites.
type DeleteRealmRolesRoleNameCompositesJSONBody = []RoleRepresentation

// PostRealmRolesRoleNameCompositesJSONBody defines parameters for PostRealmRolesRoleNameComposites.
type PostRealmRolesRoleNameCompositesJSONBody = []RoleRepresentation

// GetRealmRolesRoleNameGroupsParams defines parameters for GetRealmRolesRoleNameGroups.
type GetRealmRolesRoleNameGroupsParams struct {
	// BriefRepresentation if false, return a full representation of the GroupRepresentation objects
	BriefRepresentation *bool  `form:"briefRepresentation,omitempty" json:"briefRepresentation,omitempty"`
	First               *int32 `form:"first,omitempty" json:"first,omitempty"`
	Max                 *int32 `form:"max,omitempty" json:"max,omitempty"`
}

// GetRealmRolesRoleNameUsersParams defines parameters for GetRealmRolesRoleNameUsers.
type GetRealmRolesRoleNameUsersParams struct {
	First *int32 `form:"first,omitempty" json:"first,omitempty"`
	Max   *int32 `form:"max,omitempty" json:"max,omitempty"`
}

// PostRealmTestSMTPConnectionJSONBody defines parameters for PostRealmTestSMTPConnection.
type PostRealmTestSMTPConnectionJSONBody map[string]interface{}

// PostRealmUserStorageIdSyncParams defines parameters for PostRealmUserStorageIdSync.
type PostRealmUserStorageIdSyncParams struct {
	Action *string `form:"action,omitempty" json:"action,omitempty"`
}

// PostRealmUserStorageParentIdMappersIdSyncParams defines parameters for PostRealmUserStorageParentIdMappersIdSync.
type PostRealmUserStorageParentIdMappersIdSyncParams struct {
	Direction *string `form:"direction,omitempty" json:"direction,omitempty"`
}

// GetRealmUsersParams defines parameters for GetRealmUsers.
type GetRealmUsersParams struct {
	BriefRepresentation *bool   `form:"briefRepresentation,omitempty" json:"briefRepresentation,omitempty"`
	Email               *string `form:"email,omitempty" json:"email,omitempty"`
	First               *int32  `form:"first,omitempty" json:"first,omitempty"`
	FirstName           *string `form:"firstName,omitempty" json:"firstName,omitempty"`
	LastName            *string `form:"lastName,omitempty" json:"lastName,omitempty"`

	// Max Maximum results size (defaults to 100)
	Max *int32 `form:"max,omitempty" json:"max,omitempty"`

	// Search A String contained in username, first or last name, or email
	Search   *string `form:"search,omitempty" json:"search,omitempty"`
	Username *string `form:"username,omitempty" json:"username,omitempty"`
}

// GetRealmUsersCountParams defines parameters for GetRealmUsersCount.
type GetRealmUsersCountParams struct {
	// Email email filter
	Email *string `form:"email,omitempty" json:"email,omitempty"`

	// FirstName first name filter
	FirstName *string `form:"firstName,omitempty" json:"firstName,omitempty"`

	// LastName last name filter
	LastName *string `form:"lastName,omitempty" json:"lastName,omitempty"`

	// Search arbitrary search string for all the fields below
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// Username username filter
	Username *string `form:"username,omitempty" json:"username,omitempty"`
}

// PutRealmUsersIdCredentialsCredentialIdUserLabelTextBody defines parameters for PutRealmUsersIdCredentialsCredentialIdUserLabel.
type PutRealmUsersIdCredentialsCredentialIdUserLabelTextBody = string

// PutRealmUsersIdDisableCredentialTypesJSONBody defines parameters for PutRealmUsersIdDisableCredentialTypes.
type PutRealmUsersIdDisableCredentialTypesJSONBody = []string

// PutRealmUsersIdExecuteActionsEmailJSONBody defines parameters for PutRealmUsersIdExecuteActionsEmail.
type PutRealmUsersIdExecuteActionsEmailJSONBody = []string

// PutRealmUsersIdExecuteActionsEmailParams defines parameters for PutRealmUsersIdExecuteActionsEmail.
type PutRealmUsersIdExecuteActionsEmailParams struct {
	// ClientId Client id
	ClientId *string `form:"client_id,omitempty" json:"client_id,omitempty"`

	// Lifespan Number of seconds after which the generated token expires
	Lifespan *int32 `form:"lifespan,omitempty" json:"lifespan,omitempty"`

	// RedirectUri Redirect uri
	RedirectUri *string `form:"redirect_uri,omitempty" json:"redirect_uri,omitempty"`
}

// GetRealmUsersIdGroupsParams defines parameters for GetRealmUsersIdGroups.
type GetRealmUsersIdGroupsParams struct {
	BriefRepresentation *bool   `form:"briefRepresentation,omitempty" json:"briefRepresentation,omitempty"`
	First               *int32  `form:"first,omitempty" json:"first,omitempty"`
	Max                 *int32  `form:"max,omitempty" json:"max,omitempty"`
	Search              *string `form:"search,omitempty" json:"search,omitempty"`
}

// GetRealmUsersIdGroupsCountParams defines parameters for GetRealmUsersIdGroupsCount.
type GetRealmUsersIdGroupsCountParams struct {
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// DeleteRealmUsersIdRoleMappingsClientsClientJSONBody defines parameters for DeleteRealmUsersIdRoleMappingsClientsClient.
type DeleteRealmUsersIdRoleMappingsClientsClientJSONBody = []RoleRepresentation

// PostRealmUsersIdRoleMappingsClientsClientJSONBody defines parameters for PostRealmUsersIdRoleMappingsClientsClient.
type PostRealmUsersIdRoleMappingsClientsClientJSONBody = []RoleRepresentation

// DeleteRealmUsersIdRoleMappingsRealmJSONBody defines parameters for DeleteRealmUsersIdRoleMappingsRealm.
type DeleteRealmUsersIdRoleMappingsRealmJSONBody = []RoleRepresentation

// PostRealmUsersIdRoleMappingsRealmJSONBody defines parameters for PostRealmUsersIdRoleMappingsRealm.
type PostRealmUsersIdRoleMappingsRealmJSONBody = []RoleRepresentation

// PutRealmUsersIdSendVerifyEmailParams defines parameters for PutRealmUsersIdSendVerifyEmail.
type PutRealmUsersIdSendVerifyEmailParams struct {
	// ClientId Client id
	ClientId *string `form:"client_id,omitempty" json:"client_id,omitempty"`

	// RedirectUri Redirect uri
	RedirectUri *string `form:"redirect_uri,omitempty" json:"redirect_uri,omitempty"`
}

// PostJSONRequestBody defines body for Post for application/json ContentType.
type PostJSONRequestBody = RealmRepresentation

// PutRealmJSONRequestBody defines body for PutRealm for application/json ContentType.
type PutRealmJSONRequestBody = RealmRepresentation

// PutRealmAuthenticationConfigIdJSONRequestBody defines body for PutRealmAuthenticationConfigId for application/json ContentType.
type PutRealmAuthenticationConfigIdJSONRequestBody = AuthenticatorConfigRepresentation

// PostRealmAuthenticationExecutionsJSONRequestBody defines body for PostRealmAuthenticationExecutions for application/json ContentType.
type PostRealmAuthenticationExecutionsJSONRequestBody = AuthenticationExecutionRepresentation

// PostRealmAuthenticationExecutionsExecutionIdConfigJSONRequestBody defines body for PostRealmAuthenticationExecutionsExecutionIdConfig for application/json ContentType.
type PostRealmAuthenticationExecutionsExecutionIdConfigJSONRequestBody = AuthenticatorConfigRepresentation

// PostRealmAuthenticationFlowsJSONRequestBody defines body for PostRealmAuthenticationFlows for application/json ContentType.
type PostRealmAuthenticationFlowsJSONRequestBody = AuthenticationFlowRepresentation

// PostRealmAuthenticationFlowsFlowAliasCopyJSONRequestBody defines body for PostRealmAuthenticationFlowsFlowAliasCopy for application/json ContentType.
type PostRealmAuthenticationFlowsFlowAliasCopyJSONRequestBody PostRealmAuthenticationFlowsFlowAliasCopyJSONBody

// PutRealmAuthenticationFlowsFlowAliasExecutionsJSONRequestBody defines body for PutRealmAuthenticationFlowsFlowAliasExecutions for application/json ContentType.
type PutRealmAuthenticationFlowsFlowAliasExecutionsJSONRequestBody = AuthenticationExecutionInfoRepresentation

// PostRealmAuthenticationFlowsFlowAliasExecutionsExecutionJSONRequestBody defines body for PostRealmAuthenticationFlowsFlowAliasExecutionsExecution for application/json ContentType.
type PostRealmAuthenticationFlowsFlowAliasExecutionsExecutionJSONRequestBody PostRealmAuthenticationFlowsFlowAliasExecutionsExecutionJSONBody

// PostRealmAuthenticationFlowsFlowAliasExecutionsFlowJSONRequestBody defines body for PostRealmAuthenticationFlowsFlowAliasExecutionsFlow for application/json ContentType.
type PostRealmAuthenticationFlowsFlowAliasExecutionsFlowJSONRequestBody PostRealmAuthenticationFlowsFlowAliasExecutionsFlowJSONBody

// PutRealmAuthenticationFlowsIdJSONRequestBody defines body for PutRealmAuthenticationFlowsId for application/json ContentType.
type PutRealmAuthenticationFlowsIdJSONRequestBody = AuthenticationFlowRepresentation

// PostRealmAuthenticationRegisterRequiredActionJSONRequestBody defines body for PostRealmAuthenticationRegisterRequiredAction for application/json ContentType.
type PostRealmAuthenticationRegisterRequiredActionJSONRequestBody PostRealmAuthenticationRegisterRequiredActionJSONBody

// PutRealmAuthenticationRequiredActionsAliasJSONRequestBody defines body for PutRealmAuthenticationRequiredActionsAlias for application/json ContentType.
type PutRealmAuthenticationRequiredActionsAliasJSONRequestBody = RequiredActionProviderRepresentation

// PostRealmClientDescriptionConverterTextRequestBody defines body for PostRealmClientDescriptionConverter for text/plain ContentType.
type PostRealmClientDescriptionConverterTextRequestBody = PostRealmClientDescriptionConverterTextBody

// PostRealmClientScopesJSONRequestBody defines body for PostRealmClientScopes for application/json ContentType.
type PostRealmClientScopesJSONRequestBody = ClientScopeRepresentation

// PutRealmClientScopesId1ProtocolMappersModelsId2JSONRequestBody defines body for PutRealmClientScopesId1ProtocolMappersModelsId2 for application/json ContentType.
type PutRealmClientScopesId1ProtocolMappersModelsId2JSONRequestBody = ProtocolMapperRepresentation

// PutRealmClientScopesIdJSONRequestBody defines body for PutRealmClientScopesId for application/json ContentType.
type PutRealmClientScopesIdJSONRequestBody = ClientScopeRepresentation

// PostRealmClientScopesIdProtocolMappersAddModelsJSONRequestBody defines body for PostRealmClientScopesIdProtocolMappersAddModels for application/json ContentType.
type PostRealmClientScopesIdProtocolMappersAddModelsJSONRequestBody = PostRealmClientScopesIdProtocolMappersAddModelsJSONBody

// PostRealmClientScopesIdProtocolMappersModelsJSONRequestBody defines body for PostRealmClientScopesIdProtocolMappersModels for application/json ContentType.
type PostRealmClientScopesIdProtocolMappersModelsJSONRequestBody = ProtocolMapperRepresentation

// DeleteRealmClientScopesIdScopeMappingsClientsClientJSONRequestBody defines body for DeleteRealmClientScopesIdScopeMappingsClientsClient for application/json ContentType.
type DeleteRealmClientScopesIdScopeMappingsClientsClientJSONRequestBody = DeleteRealmClientScopesIdScopeMappingsClientsClientJSONBody

// PostRealmClientScopesIdScopeMappingsClientsClientJSONRequestBody defines body for PostRealmClientScopesIdScopeMappingsClientsClient for application/json ContentType.
type PostRealmClientScopesIdScopeMappingsClientsClientJSONRequestBody = PostRealmClientScopesIdScopeMappingsClientsClientJSONBody

// DeleteRealmClientScopesIdScopeMappingsRealmJSONRequestBody defines body for DeleteRealmClientScopesIdScopeMappingsRealm for application/json ContentType.
type DeleteRealmClientScopesIdScopeMappingsRealmJSONRequestBody = DeleteRealmClientScopesIdScopeMappingsRealmJSONBody

// PostRealmClientScopesIdScopeMappingsRealmJSONRequestBody defines body for PostRealmClientScopesIdScopeMappingsRealm for application/json ContentType.
type PostRealmClientScopesIdScopeMappingsRealmJSONRequestBody = PostRealmClientScopesIdScopeMappingsRealmJSONBody

// PostRealmClientsJSONRequestBody defines body for PostRealmClients for application/json ContentType.
type PostRealmClientsJSONRequestBody = ClientRepresentation

// PostRealmClientsInitialAccessJSONRequestBody defines body for PostRealmClientsInitialAccess for application/json ContentType.
type PostRealmClientsInitialAccessJSONRequestBody = ClientInitialAccessCreatePresentation

// PutRealmClientsId1ProtocolMappersModelsId2JSONRequestBody defines body for PutRealmClientsId1ProtocolMappersModelsId2 for application/json ContentType.
type PutRealmClientsId1ProtocolMappersModelsId2JSONRequestBody = ProtocolMapperRepresentation

// PutRealmClientsIdJSONRequestBody defines body for PutRealmClientsId for application/json ContentType.
type PutRealmClientsIdJSONRequestBody = ClientRepresentation

// PostRealmClientsIdCertificatesAttrDownloadJSONRequestBody defines body for PostRealmClientsIdCertificatesAttrDownload for application/json ContentType.
type PostRealmClientsIdCertificatesAttrDownloadJSONRequestBody = KeyStoreConfig

// PostRealmClientsIdCertificatesAttrGenerateAndDownloadJSONRequestBody defines body for PostRealmClientsIdCertificatesAttrGenerateAndDownload for application/json ContentType.
type PostRealmClientsIdCertificatesAttrGenerateAndDownloadJSONRequestBody = KeyStoreConfig

// PutRealmClientsIdManagementPermissionsJSONRequestBody defines body for PutRealmClientsIdManagementPermissions for application/json ContentType.
type PutRealmClientsIdManagementPermissionsJSONRequestBody = ManagementPermissionReference

// PostRealmClientsIdNodesJSONRequestBody defines body for PostRealmClientsIdNodes for application/json ContentType.
type PostRealmClientsIdNodesJSONRequestBody PostRealmClientsIdNodesJSONBody

// PostRealmClientsIdProtocolMappersAddModelsJSONRequestBody defines body for PostRealmClientsIdProtocolMappersAddModels for application/json ContentType.
type PostRealmClientsIdProtocolMappersAddModelsJSONRequestBody = PostRealmClientsIdProtocolMappersAddModelsJSONBody

// PostRealmClientsIdProtocolMappersModelsJSONRequestBody defines body for PostRealmClientsIdProtocolMappersModels for application/json ContentType.
type PostRealmClientsIdProtocolMappersModelsJSONRequestBody = ProtocolMapperRepresentation

// PostRealmClientsIdRolesJSONRequestBody defines body for PostRealmClientsIdRoles for application/json ContentType.
type PostRealmClientsIdRolesJSONRequestBody = RoleRepresentation

// PutRealmClientsIdRolesRoleNameJSONRequestBody defines body for PutRealmClientsIdRolesRoleName for application/json ContentType.
type PutRealmClientsIdRolesRoleNameJSONRequestBody = RoleRepresentation

// DeleteRealmClientsIdRolesRoleNameCompositesJSONRequestBody defines body for DeleteRealmClientsIdRolesRoleNameComposites for application/json ContentType.
type DeleteRealmClientsIdRolesRoleNameCompositesJSONRequestBody = DeleteRealmClientsIdRolesRoleNameCompositesJSONBody

// PostRealmClientsIdRolesRoleNameCompositesJSONRequestBody defines body for PostRealmClientsIdRolesRoleNameComposites for application/json ContentType.
type PostRealmClientsIdRolesRoleNameCompositesJSONRequestBody = PostRealmClientsIdRolesRoleNameCompositesJSONBody

// PutRealmClientsIdRolesRoleNameManagementPermissionsJSONRequestBody defines body for PutRealmClientsIdRolesRoleNameManagementPermissions for application/json ContentType.
type PutRealmClientsIdRolesRoleNameManagementPermissionsJSONRequestBody = ManagementPermissionReference

// DeleteRealmClientsIdScopeMappingsClientsClientJSONRequestBody defines body for DeleteRealmClientsIdScopeMappingsClientsClient for application/json ContentType.
type DeleteRealmClientsIdScopeMappingsClientsClientJSONRequestBody = DeleteRealmClientsIdScopeMappingsClientsClientJSONBody

// PostRealmClientsIdScopeMappingsClientsClientJSONRequestBody defines body for PostRealmClientsIdScopeMappingsClientsClient for application/json ContentType.
type PostRealmClientsIdScopeMappingsClientsClientJSONRequestBody = PostRealmClientsIdScopeMappingsClientsClientJSONBody

// DeleteRealmClientsIdScopeMappingsRealmJSONRequestBody defines body for DeleteRealmClientsIdScopeMappingsRealm for application/json ContentType.
type DeleteRealmClientsIdScopeMappingsRealmJSONRequestBody = DeleteRealmClientsIdScopeMappingsRealmJSONBody

// PostRealmClientsIdScopeMappingsRealmJSONRequestBody defines body for PostRealmClientsIdScopeMappingsRealm for application/json ContentType.
type PostRealmClientsIdScopeMappingsRealmJSONRequestBody = PostRealmClientsIdScopeMappingsRealmJSONBody

// PostRealmComponentsJSONRequestBody defines body for PostRealmComponents for application/json ContentType.
type PostRealmComponentsJSONRequestBody = ComponentRepresentation

// PutRealmComponentsIdJSONRequestBody defines body for PutRealmComponentsId for application/json ContentType.
type PutRealmComponentsIdJSONRequestBody = ComponentRepresentation

// PutRealmEventsConfigJSONRequestBody defines body for PutRealmEventsConfig for application/json ContentType.
type PutRealmEventsConfigJSONRequestBody = RealmEventsConfigRepresentation

// PostRealmGroupsJSONRequestBody defines body for PostRealmGroups for application/json ContentType.
type PostRealmGroupsJSONRequestBody = GroupRepresentation

// PutRealmGroupsIdJSONRequestBody defines body for PutRealmGroupsId for application/json ContentType.
type PutRealmGroupsIdJSONRequestBody = GroupRepresentation

// PostRealmGroupsIdChildrenJSONRequestBody defines body for PostRealmGroupsIdChildren for application/json ContentType.
type PostRealmGroupsIdChildrenJSONRequestBody = GroupRepresentation

// PutRealmGroupsIdManagementPermissionsJSONRequestBody defines body for PutRealmGroupsIdManagementPermissions for application/json ContentType.
type PutRealmGroupsIdManagementPermissionsJSONRequestBody = ManagementPermissionReference

// DeleteRealmGroupsIdRoleMappingsClientsClientJSONRequestBody defines body for DeleteRealmGroupsIdRoleMappingsClientsClient for application/json ContentType.
type DeleteRealmGroupsIdRoleMappingsClientsClientJSONRequestBody = DeleteRealmGroupsIdRoleMappingsClientsClientJSONBody

// PostRealmGroupsIdRoleMappingsClientsClientJSONRequestBody defines body for PostRealmGroupsIdRoleMappingsClientsClient for application/json ContentType.
type PostRealmGroupsIdRoleMappingsClientsClientJSONRequestBody = PostRealmGroupsIdRoleMappingsClientsClientJSONBody

// DeleteRealmGroupsIdRoleMappingsRealmJSONRequestBody defines body for DeleteRealmGroupsIdRoleMappingsRealm for application/json ContentType.
type DeleteRealmGroupsIdRoleMappingsRealmJSONRequestBody = DeleteRealmGroupsIdRoleMappingsRealmJSONBody

// PostRealmGroupsIdRoleMappingsRealmJSONRequestBody defines body for PostRealmGroupsIdRoleMappingsRealm for application/json ContentType.
type PostRealmGroupsIdRoleMappingsRealmJSONRequestBody = PostRealmGroupsIdRoleMappingsRealmJSONBody

// PostRealmIdentityProviderInstancesJSONRequestBody defines body for PostRealmIdentityProviderInstances for application/json ContentType.
type PostRealmIdentityProviderInstancesJSONRequestBody = IdentityProviderRepresentation

// PutRealmIdentityProviderInstancesAliasJSONRequestBody defines body for PutRealmIdentityProviderInstancesAlias for application/json ContentType.
type PutRealmIdentityProviderInstancesAliasJSONRequestBody = IdentityProviderRepresentation

// PutRealmIdentityProviderInstancesAliasManagementPermissionsJSONRequestBody defines body for PutRealmIdentityProviderInstancesAliasManagementPermissions for application/json ContentType.
type PutRealmIdentityProviderInstancesAliasManagementPermissionsJSONRequestBody = ManagementPermissionReference

// PostRealmIdentityProviderInstancesAliasMappersJSONRequestBody defines body for PostRealmIdentityProviderInstancesAliasMappers for application/json ContentType.
type PostRealmIdentityProviderInstancesAliasMappersJSONRequestBody = IdentityProviderMapperRepresentation

// PutRealmIdentityProviderInstancesAliasMappersIdJSONRequestBody defines body for PutRealmIdentityProviderInstancesAliasMappersId for application/json ContentType.
type PutRealmIdentityProviderInstancesAliasMappersIdJSONRequestBody = IdentityProviderMapperRepresentation

// PostRealmPartialImportJSONRequestBody defines body for PostRealmPartialImport for application/json ContentType.
type PostRealmPartialImportJSONRequestBody = PartialImportRepresentation

// PostRealmRolesJSONRequestBody defines body for PostRealmRoles for application/json ContentType.
type PostRealmRolesJSONRequestBody = RoleRepresentation

// PutRealmRolesByIdRoleIdJSONRequestBody defines body for PutRealmRolesByIdRoleId for application/json ContentType.
type PutRealmRolesByIdRoleIdJSONRequestBody = RoleRepresentation

// DeleteRealmRolesByIdRoleIdCompositesJSONRequestBody defines body for DeleteRealmRolesByIdRoleIdComposites for application/json ContentType.
type DeleteRealmRolesByIdRoleIdCompositesJSONRequestBody = DeleteRealmRolesByIdRoleIdCompositesJSONBody

// PostRealmRolesByIdRoleIdCompositesJSONRequestBody defines body for PostRealmRolesByIdRoleIdComposites for application/json ContentType.
type PostRealmRolesByIdRoleIdCompositesJSONRequestBody = PostRealmRolesByIdRoleIdCompositesJSONBody

// PutRealmRolesByIdRoleIdManagementPermissionsJSONRequestBody defines body for PutRealmRolesByIdRoleIdManagementPermissions for application/json ContentType.
type PutRealmRolesByIdRoleIdManagementPermissionsJSONRequestBody = ManagementPermissionReference

// PutRealmRolesRoleNameJSONRequestBody defines body for PutRealmRolesRoleName for application/json ContentType.
type PutRealmRolesRoleNameJSONRequestBody = RoleRepresentation

// DeleteRealmRolesRoleNameCompositesJSONRequestBody defines body for DeleteRealmRolesRoleNameComposites for application/json ContentType.
type DeleteRealmRolesRoleNameCompositesJSONRequestBody = DeleteRealmRolesRoleNameCompositesJSONBody

// PostRealmRolesRoleNameCompositesJSONRequestBody defines body for PostRealmRolesRoleNameComposites for application/json ContentType.
type PostRealmRolesRoleNameCompositesJSONRequestBody = PostRealmRolesRoleNameCompositesJSONBody

// PutRealmRolesRoleNameManagementPermissionsJSONRequestBody defines body for PutRealmRolesRoleNameManagementPermissions for application/json ContentType.
type PutRealmRolesRoleNameManagementPermissionsJSONRequestBody = ManagementPermissionReference

// PostRealmTestLDAPConnectionJSONRequestBody defines body for PostRealmTestLDAPConnection for application/json ContentType.
type PostRealmTestLDAPConnectionJSONRequestBody = TestLdapConnectionRepresentation

// PostRealmTestSMTPConnectionJSONRequestBody defines body for PostRealmTestSMTPConnection for application/json ContentType.
type PostRealmTestSMTPConnectionJSONRequestBody PostRealmTestSMTPConnectionJSONBody

// PostRealmUsersJSONRequestBody defines body for PostRealmUsers for application/json ContentType.
type PostRealmUsersJSONRequestBody = UserRepresentation

// PutRealmUsersManagementPermissionsJSONRequestBody defines body for PutRealmUsersManagementPermissions for application/json ContentType.
type PutRealmUsersManagementPermissionsJSONRequestBody = ManagementPermissionReference

// PutRealmUsersIdJSONRequestBody defines body for PutRealmUsersId for application/json ContentType.
type PutRealmUsersIdJSONRequestBody = UserRepresentation

// PutRealmUsersIdCredentialsCredentialIdUserLabelTextRequestBody defines body for PutRealmUsersIdCredentialsCredentialIdUserLabel for text/plain ContentType.
type PutRealmUsersIdCredentialsCredentialIdUserLabelTextRequestBody = PutRealmUsersIdCredentialsCredentialIdUserLabelTextBody

// PutRealmUsersIdDisableCredentialTypesJSONRequestBody defines body for PutRealmUsersIdDisableCredentialTypes for application/json ContentType.
type PutRealmUsersIdDisableCredentialTypesJSONRequestBody = PutRealmUsersIdDisableCredentialTypesJSONBody

// PutRealmUsersIdExecuteActionsEmailJSONRequestBody defines body for PutRealmUsersIdExecuteActionsEmail for application/json ContentType.
type PutRealmUsersIdExecuteActionsEmailJSONRequestBody = PutRealmUsersIdExecuteActionsEmailJSONBody

// PostRealmUsersIdFederatedIdentityProviderJSONRequestBody defines body for PostRealmUsersIdFederatedIdentityProvider for application/json ContentType.
type PostRealmUsersIdFederatedIdentityProviderJSONRequestBody = FederatedIdentityRepresentation

// PutRealmUsersIdResetPasswordJSONRequestBody defines body for PutRealmUsersIdResetPassword for application/json ContentType.
type PutRealmUsersIdResetPasswordJSONRequestBody = CredentialRepresentation

// DeleteRealmUsersIdRoleMappingsClientsClientJSONRequestBody defines body for DeleteRealmUsersIdRoleMappingsClientsClient for application/json ContentType.
type DeleteRealmUsersIdRoleMappingsClientsClientJSONRequestBody = DeleteRealmUsersIdRoleMappingsClientsClientJSONBody

// PostRealmUsersIdRoleMappingsClientsClientJSONRequestBody defines body for PostRealmUsersIdRoleMappingsClientsClient for application/json ContentType.
type PostRealmUsersIdRoleMappingsClientsClientJSONRequestBody = PostRealmUsersIdRoleMappingsClientsClientJSONBody

// DeleteRealmUsersIdRoleMappingsRealmJSONRequestBody defines body for DeleteRealmUsersIdRoleMappingsRealm for application/json ContentType.
type DeleteRealmUsersIdRoleMappingsRealmJSONRequestBody = DeleteRealmUsersIdRoleMappingsRealmJSONBody

// PostRealmUsersIdRoleMappingsRealmJSONRequestBody defines body for PostRealmUsersIdRoleMappingsRealm for application/json ContentType.
type PostRealmUsersIdRoleMappingsRealmJSONRequestBody = PostRealmUsersIdRoleMappingsRealmJSONBody
