apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-manager-writer
rules:
  - apiGroups: 
    - ""
    resources: 
    - "secrets"
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch