# permissions for end users to edit identityproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: identity-operator
    app.kubernetes.io/managed-by: kustomize
  name: identityprovider-editor-role
rules:
- apiGroups:
  - identity.cp.ei.telekom.de
  resources:
  - identityproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - identity.cp.ei.telekom.de
  resources:
  - identityproviders/status
  verbs:
  - get
