# permissions for end users to view identityproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: identity-operator
    app.kubernetes.io/managed-by: kustomize
  name: identityprovider-viewer-role
rules:
- apiGroups:
  - identity.cp.ei.telekom.de
  resources:
  - identityproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - identity.cp.ei.telekom.de
  resources:
  - identityproviders/status
  verbs:
  - get
