---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - identity.cp.ei.telekom.de
  resources:
  - clients
  - identityproviders
  - realms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - identity.cp.ei.telekom.de
  resources:
  - clients/finalizers
  - identityproviders/finalizers
  - realms/finalizers
  verbs:
  - update
- apiGroups:
  - identity.cp.ei.telekom.de
  resources:
  - clients/status
  - identityproviders/status
  - realms/status
  verbs:
  - get
  - patch
  - update
