ort:
  # Allows defining package configs/curations in the repository's .ort.yml file
  enableRepositoryPackageConfigurations: true
  enableRepositoryPackageCurations: true

  # These could be used to not treat warnings as severe issues
  #severeIssueThreshold: ERROR
  #severeRuleViolationThreshold: ERROR

  # Force overwriting of existing reports
  forceOverwrite: true

  analyzer:
    # Allow version ranges in dependency specifications
    allowDynamicVersions: true
    skipExcluded: true
  downloader:
    skipExcluded: true
    # Allow downloads using symbolic names that point to moving revisions, like Git branches
    allowMovingRevisions: true
  scanner:
    storages:
      # Read/write results to actions cache
      local:
        backend:
          localFileStorage:
            directory: /home/ort/.ort/scanner/results
            compression: false
    storageReaders: ["local"]
    storageWriters: ["local"]
    skipExcluded: true
    skipConcluded: true
  advisor:
    skipExcluded: true

excludes:
  paths:
  - pattern: "test-data/**"
    reason: "TEST_OF"
    comment: "This directory contains test data which are not distributed."
  - pattern: CONTRIBUTING.md
    reason: DOCUMENTATION_OF
    comment: "This file contains contribution guidelines which are not distributed."
  - pattern: README.md	
    reason: DOCUMENTATION_OF
    comment: "This file contains project description which is not distributed."
  - pattern: ".github/**"
    reason: "BUILD_TOOL_OF"
    comment: "This directory contains GitHub Actions workflows which are not distributed."
  - pattern: "*_test.go"
    reason: "TEST_OF"
    comment: "This file contains test code which is not distributed."
  - pattern: "test_*.go"
    reason: "TEST_OF"
    comment: "This file contains test code which is not distributed."