ort:
  # Allows defining package configs/curations in the repository's .ort.yml file
  enableRepositoryPackageConfigurations: true
  enableRepositoryPackageCurations: true

  # These could be used to not treat warnings as severe issues
  #severeIssueThreshold: ERROR
  #severeRuleViolationThreshold: ERROR

  # Force overwriting of existing reports
  forceOverwrite: true

  analyzer:
    # Allow version ranges in dependency specifications
    allowDynamicVersions: true
    skipExcluded: true
  downloader:
    skipExcluded: true
    # Allow downloads using symbolic names that point to moving revisions, like Git branches
    allowMovingRevisions: true
  scanner:
    storages:
      # Read/write results to actions cache
      local:
        backend:
          localFileStorage:
            directory: /home/ort/.ort/scanner/results
            compression: false
    storageReaders: ["local"]
    storageWriters: ["local"]
    skipExcluded: true
  advisor:
    skipExcluded: true