name: Run CI

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - "main"

env:
  OPERATORS: '["gateway", "identity"]'
  ALL_MODULES: '["common", "common-server", "gateway"]' # Updated for example

jobs:
  prepare:
    name: detect modules
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.matrix.outputs.modules }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # pin@v2.0.0
      - name: Detect Changes
        id: detect-changes
        uses: ron96G/monutil@v1.3.0
        with:
          base-commit: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event_name == 'push' && github.event.before }}
          head-commit: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.event_name == 'push' && github.sha }}
      - name: Build Matrix
        id: matrix
        run: |
          echo "modules=${{ toJson(env.ALL_MODULES) }}" >> $GITHUB_OUTPUT

  operator-ci:
    name: Operator CI for ${{ matrix.module }}
    uses: ./.github/workflows/reusable-go-ci.yaml
    needs: prepare
    with:
      module: ${{ matrix.module }}
      run_check_generated_files: true
      run_build_image: true
      run_tests: false
      ko_build_path: "cmd/main.go"

    permissions:
      contents: read
      pull-requests: write
      checks: write
      security-events: write
      packages: read
      actions: read
    strategy:
      matrix:
        module:
          - "identity"
          - "gateway"
