name: golangci-lint

on:
  workflow_dispatch:
  push:
    paths:
      - 'common/**'
      - 'common-server/**'
      - 'secret-manager/**'
      - 'gateway/**'
      - 'identity/**'
  pull_request:
    branches:
      - "main"
    paths:
      - 'common/**'
      - 'common-server/**'
      - 'secret-manager/**'
      - 'gateway/**'
      - 'identity/**'

permissions:
  # Required: allow read access to the content for analysis.
  contents: read

env:
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v2.1

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - common
          - common-server
          - secret-manager
          - gateway
          - identity
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # pin@5.5.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 #pin@8.0.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: ${{ matrix.module }}